package ads.ad;

import java.io.IOException;
import java.io.PrintWriter;
import java.math.BigDecimal;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.ArrayList;
import java.util.Locale;

import ads.objects.Administrator;
import ads.objects.Booking;
import ads.user.AdministratorFunction;
import ads.user.AdministratorFunctionImpl;
import jakarta.servlet.RequestDispatcher;
import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import jakarta.servlet.http.HttpSession;

@WebServlet("/ad/profile-management")
public class ProfileManagementServlet extends HttpServlet {
	private AdministratorFunction administratorFunction = new AdministratorFunctionImpl();

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Override
	protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
		resp.setCharacterEncoding("UTF-8");
		resp.setContentType("text/html; charset=UTF-8");

		HttpSession session = req.getSession(false);
		if (session == null || session.getAttribute("username") == null) {
			resp.sendRedirect(req.getContextPath() + "/ad/login");
			return;
		}

		String username = (String) session.getAttribute("username");
		
		// Thông tin admin
		Administrator administrator = administratorFunction.getAdministratorByUsername(username);
		

		PrintWriter out = resp.getWriter();

		out.append("<!DOCTYPE html>");
		out.append("<html lang=\"en\">");
		out.append("");
		out.append("<head>");
		out.append("  <meta charset=\"utf-8\">");
		out.append("  <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">");
		out.append("");
		out.append("  <title>TravelVN - Hồ sơ</title>");
		out.append("  <meta content=\"\" name=\"description\">");
		out.append("  <meta content=\"\" name=\"keywords\">");
		out.append("");
		out.append("  <!-- Favicons -->");
		out.append("  <link href=\"/adv/assets/img/Logo.svg\" rel=\"icon\">");
		out.append("  <link href=\"/adv/assets/img/apple-touch-icon.png\" rel=\"apple-touch-icon\">");
		out.append("");
		out.append("  <!-- Google Fonts -->");
		out.append("  <link href=\"https://fonts.gstatic.com\" rel=\"preconnect\">");
		out.append("  <link");
		out.append("    href=\"https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i\"");
		out.append("    rel=\"stylesheet\">");
		out.append("");
		out.append("  <!-- Vendor CSS Files -->");
		out.append("  <link href=\"/adv/assets/vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">");
		out.append("  <link href=\"/adv/assets/vendor/bootstrap-icons/bootstrap-icons.css\" rel=\"stylesheet\">");
		out.append("  <link href=\"/adv/assets/vendor/boxicons/css/boxicons.min.css\" rel=\"stylesheet\">");
		out.append("  <link href=\"/adv/assets/vendor/quill/quill.snow.css\" rel=\"stylesheet\">");
		out.append("  <link href=\"/adv/assets/vendor/quill/quill.bubble.css\" rel=\"stylesheet\">");
		out.append("  <link href=\"/adv/assets/vendor/remixicon/remixicon.css\" rel=\"stylesheet\">");
		out.append("  <link href=\"/adv/assets/vendor/simple-datatables/style.css\" rel=\"stylesheet\">");
		out.append("");
		out.append("  <!-- Template Main CSS File -->");
		out.append("  <link href=\"/adv/assets/css/style.css\" rel=\"stylesheet\">");
		out.append("");
		out.append("  <!-- =======================================================");
		out.append("  * Template Name: NiceAdmin");
		out.append("  * Template URL: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/");
		out.append("  * Updated: Apr 20 2024 with Bootstrap v5.3.3");
		out.append("  * Author: BootstrapMade.com");
		out.append("  * License: https://bootstrapmade.com/license/");
		out.append("  ======================================================== -->");
		out.append("</head>");
		out.append("");
		out.append("<body>");
		out.append("");
//		out.append("  <!-- ======= Header ======= -->");
//		out.append("  <header id=\"header\" class=\"header fixed-top d-flex align-items-center\">");
//		out.append("");
//		out.append("    <div class=\"d-flex align-items-center justify-content-between\">");
//		out.append("      <a href=\"index.html\" class=\"logo d-flex align-items-center\">");
//		out.append("        <img src=\"/adv/assets/img/Logo.svg\" alt=\"\">");
//		out.append("        <span class=\"d-none d-lg-block\">TravelVN</span>");
//		out.append("      </a>");
//		out.append("      <i class=\"bi bi-list toggle-sidebar-btn\"></i>");
//		out.append("    </div><!-- End Logo -->");
//		out.append("");
//		out.append("");
//		out.append("    <nav class=\"header-nav ms-auto\">");
//		out.append("      <ul class=\"d-flex align-items-center\">");
//		out.append("");
//		out.append("        <li class=\"nav-item dropdown pe-3\">");
//		out.append("");
//		out.append("          <a class=\"nav-link nav-profile d-flex align-items-center pe-0\" href=\"#\" data-bs-toggle=\"dropdown\">");
//		out.append("            <span class=\"d-none d-md-block dropdown-toggle ps-2\">" + username + "</span>");
//		out.append("          </a>");
//		out.append("");
//		out.append("          <ul class=\"dropdown-menu dropdown-menu-end dropdown-menu-arrow profile\">");
//		out.append("            <li class=\"dropdown-header\">");
//		out.append("              <h6>" + username + "</h6>");
//		out.append("              <span>Người quản lý</span>");
//		out.append("            </li>");
//		out.append("            <li>");
//		out.append("              <hr class=\"dropdown-divider\">");
//		out.append("            </li>");
//		out.append("");
//		out.append("            <li>");
//		out.append("              <a class=\"dropdown-item d-flex align-items-center\" href=\"" + req.getContextPath() + "/ad/profile-management\">");
//		out.append("                <i class=\"bi bi-person\"></i>");
//		out.append("                <span>Hồ sơ của tôi</span>");
//		out.append("              </a>");
//		out.append("            </li>");
//		out.append("            <li>");
//		out.append("              <hr class=\"dropdown-divider\">");
//		out.append("            </li>");
//		out.append("            <li>");
//		out.append("              <a class=\"dropdown-item d-flex align-items-center\" href=\"#\">");
//		out.append("                <i class=\"bi bi-box-arrow-right\"></i>");
//		out.append("                <span>Đăng xuất</span>");
//		out.append("              </a>");
//		out.append("            </li>");
//		out.append("");
//		out.append("          </ul><!-- End Profile Dropdown Items -->");
//		out.append("        </li><!-- End Profile Nav -->");
//		out.append("");
//		out.append("      </ul>");
//		out.append("    </nav><!-- End Icons Navigation -->");
//		out.append("");
//		out.append("  </header><!-- End Header -->");
		
		RequestDispatcher h = req.getRequestDispatcher("/heAd");
		if (h != null) {
			h.include(req, resp);
		}
		
		out.append("");
		out.append("    <!-- ======= Sidebar ======= -->");
		out.append("    <aside id=\"sidebar\" class=\"sidebar\">");
		out.append("");
		out.append("        <ul class=\"sidebar-nav\" id=\"sidebar-nav\">");
		out.append("");
		out.append("            <!-- Dashboard Nav -->");
		out.append("            <li class=\"nav-item\">");
		out.append("                <a class=\"nav-link\" href=\"" + req.getContextPath() + "/ad/ad-dashboard\">");
		out.append("                    <i class=\"bx bx-category\"></i>");
		out.append("                    <span>Tổng quan</span>");
		out.append("                </a>");
		out.append("            </li>");
		out.append("            <!-- End Dashboard Nav -->");
		out.append("");
		out.append("            <!-- Account Management Nav -->");
		out.append("            <li class=\"nav-item\">");
		out.append("                <a class=\"nav-link collapsed\" href=\"" + req.getContextPath() + "/ad/account-management\">");
		out.append("                    <i class=\"bx bx-user-circle\"></i>");
		out.append("                    <span>Quản lý tài khoản</span>");
		out.append("                </a>");
		out.append("            </li>");
		out.append("            <!-- End Account Management Nav -->");
		out.append("");
		out.append("            <!-- Staff Management Nav -->");
		out.append("            <li class=\"nav-item\">");
		out.append("                <a class=\"nav-link collapsed\" data-bs-target=\"#staff-management-nav\" data-bs-toggle=\"collapse\" href=\"#\">");
		out.append("                    <i class=\"bx bx-user\"></i><span>Quản lý nhân viên</span><i class=\"bi bi-chevron-down ms-auto\"></i>");
		out.append("                </a>");
		out.append("                <ul id=\"staff-management-nav\" class=\"nav-content collapse \" data-bs-parent=\"#sidebar-nav\">");
		out.append("                    <li>");
		out.append("                        <a href=\"" + req.getContextPath() + "/ad/touroperator-management\">");
		out.append("              				<i class=\"bi bi-circle\"></i><span style=\"font-size: 12px;\">Điều hành Tour</span>");
		out.append("                        </a>");
		out.append("                    </li>");
		out.append("                    <li>");
		out.append("                        <a href=\"" + req.getContextPath() + "/ad/tourguide-management\">");
		out.append("              				<i class=\"bi bi-circle\"></i><span style=\"font-size: 12px;\">Hướng dẫn viên</span>");
		out.append("                        </a>");
		out.append("                    </li>");
		out.append("                </ul>");
		out.append("            </li>");
		out.append("            <!-- End Staff Management Nav -->");
		out.append("");
		out.append("            <!-- Customer Management Nav -->");
		out.append("            <li class=\"nav-item\">");
		out.append("                <a class=\"nav-link collapsed\" href=\"" + req.getContextPath() + "/ad/customer-management\">");
		out.append("                    <i class=\"bx bx-group\"></i>");
		out.append("                    <span>Quản lý khách hàng</span>");
		out.append("                </a>");
		out.append("            </li>");
		out.append("            <!-- End Customer Management Nav -->");
		out.append("");
		out.append("            <!-- Tour Management Nav -->");
		out.append("            <li class=\"nav-item\">");
		out.append("                <a class=\"nav-link collapsed\" href=\"" + req.getContextPath() + "/ad/tour-management\">");
		out.append("                    <i class=\"bx bx-food-menu\"></i>");
		out.append("                    <span>Quản lý Tour</span>");
		out.append("                </a>");
		out.append("            </li>");
		out.append("            <!-- End Tour Management Nav -->");
		out.append("");
		out.append("            <!-- Review Management Nav -->");
		out.append("            <li class=\"nav-item\">");
		out.append("                <a class=\"nav-link collapsed\" href=\"" + req.getContextPath() + "/ad/tourrating-management\">");
		out.append("                    <i class=\"bx bx-message-square-detail\"></i>");
		out.append("                    <span>Duyệt đánh giá</span>");
		out.append("                </a>");
		out.append("            </li>");
		out.append("            <!-- End Review Management Nav -->");
		out.append("        </ul>");
		out.append("");
		out.append("    </aside><!-- End Sidebar-->");
		out.append("");
		out.append("  <main id=\"main\" class=\"main\">");
		out.append("");
		out.append("    <div class=\"pagetitle d-flex\">");
		out.append("      <h1>Hồ sơ</h1>");
		out.append("      <nav class=\"ms-auto\">");
		out.append("        <ol class=\"breadcrumb\">");
		out.append("          <li class=\"breadcrumb-item active\">Hồ sơ</li>");
		out.append("        </ol>");
		out.append("      </nav>");
		out.append("    </div><!-- End Page Title -->");
		out.append("");
		out.append("    <section class=\"section profile\">");
		out.append("      <div class=\"row\">");
		out.append("");
		out.append("        <div class=\"col-xl-12\">");
		out.append("");
		out.append("          <div class=\"card\">");
		out.append("            <div class=\"card-body pt-3\">");
		out.append("              <!-- Bordered Tabs -->");
		out.append("              <ul class=\"nav nav-tabs nav-tabs-bordered\">");
		out.append("                <li class=\"nav-item\">");
		out.append("                  <button class=\"nav-link active d-flex align-items-center\" data-bs-toggle=\"tab\"");
		out.append("                    data-bs-target=\"#profile-overview\"><i class=\"bx bx-info-circle me-1\"></i>Tổng quan</button>");
		out.append("                </li>");
		out.append("");
		out.append("                <li class=\"nav-item\">");
		out.append("                  <button class=\"nav-link d-flex align-items-center\" data-bs-toggle=\"tab\"");
		out.append("                    data-bs-target=\"#profile-edit\"><i class=\"bx bx-pencil me-1\"></i>Sửa hồ sơ</button>");
		out.append("                </li>");
		out.append("");
		out.append("                <li class=\"nav-item\">");
		out.append("                  <button class=\"nav-link d-flex align-items-center\" data-bs-toggle=\"tab\"");
		out.append("                    data-bs-target=\"#profile-change-password\"><i class=\"bx bx-lock me-1\"></i>Đổi mật khẩu</button>");
		out.append("                </li>");
		out.append("              </ul>");
		out.append("              <div class=\"tab-content pt-2\">");
		out.append("");
		out.append("                <div class=\"tab-pane fade show active profile-overview\" id=\"profile-overview\">");
		out.append("");
		out.append("                  <div class=\"row mt-3\">");
		out.append("                    <div class=\"col-lg-1 col-md-4 label\">Công ty</div>");
		out.append("                    <div class=\"col-lg-11 col-md-8\">TravelVN</div>");
		out.append("                  </div>");
		out.append("");
		
		// Hồ sơ
		out.append("                  <div class=\"row\">");
		out.append("                    <div class=\"col-lg-1 col-md-4 label\">Email</div>");
		out.append("                    <div class=\"col-lg-11 col-md-8\">" + administrator.getUserAccount().getEmail() + "</div>");
		out.append("                  </div>");
		out.append("");
		out.append("                </div>");
		out.append("");
		out.append("                <div class=\"tab-pane fade profile-edit pt-3\" id=\"profile-edit\">");
		out.append("");
		
		// Sửa hồ sơ
		out.append("                  <!-- Profile Edit Form -->");
		out.append("                  <form action=\"" + req.getContextPath() + "/ad/profile-management/update\" method=\"POST\">");
		out.append("                    <div class=\"row mb-3\">");
		out.append("                      <label for=\"company\" class=\"col-md-4 col-lg-1 col-form-label\">Công ty</label>");
		out.append("                      <div class=\"col-md-8 col-lg-11\">");
		out.append("                        <input name=\"company\" type=\"text\" class=\"form-control\" id=\"company\" value=\"TravelVN\" disabled>");
		out.append("                      </div>");
		out.append("                    </div>");
		out.append("");
		out.append("                    <div class=\"row mb-3\">");
		out.append("                      <label for=\"Email\" class=\"col-md-4 col-lg-1 col-form-label\">Email</label>");
		out.append("                      <div class=\"col-md-8 col-lg-11\">");
		out.append("                        <input name=\"username\" type=\"hidden\" class=\"form-control\" id=\"username\" value=\"" + username + "\">");
		out.append("                        <input name=\"email\" type=\"email\" class=\"form-control\" id=\"Email\" value=\"" + administrator.getUserAccount().getEmail() + "\">");
		out.append("                      </div>");
		out.append("                    </div>");
		out.append("");
		out.append("                    <div class=\"text-center\">");
		out.append("                      <button type=\"submit\" class=\"btn btn-primary\">Lưu thay đổi</button>");
		out.append("                    </div>");
		out.append("                  </form><!-- End Profile Edit Form -->");
		out.append("");
		out.append("                </div>");
		out.append("");
		
		// Đổi mật khẩu
		out.append("                <div class=\"tab-pane fade pt-3\" id=\"profile-change-password\">");
		out.append("                  <!-- Change Password Form -->");
		out.append("                  <form action=\"" + req.getContextPath() + "/ad/profile-management/change-password\" method=\"POST\">");
		out.append("");
		out.append("                    <input name=\"username\" type=\"hidden\" class=\"form-control\" id=\"username\" value=\"" + username + "\">");
		out.append("                    <div class=\"row mb-3\">");
		out.append("                      <label for=\"currentPassword\" class=\"col-md-4 col-lg-2 col-form-label\">Mật khẩu hiện tại</label>");
		out.append("                      <div class=\"col-md-8 col-lg-10\">");
		out.append("                        <input name=\"currentPassword\" type=\"password\" class=\"form-control\" id=\"currentPassword\">");
		out.append("                      </div>");
		out.append("                    </div>");
		out.append("");
		out.append("                    <div class=\"row mb-3\">");
		out.append("                      <label for=\"newPassword\" class=\"col-md-4 col-lg-2 col-form-label\">Mật khẩu mới</label>");
		out.append("                      <div class=\"col-md-8 col-lg-10\">");
		out.append("                        <input name=\"newPassword\" type=\"password\" class=\"form-control\" id=\"newPassword\">");
		out.append("                      </div>");
		out.append("                    </div>");
		out.append("");
		out.append("                    <div class=\"row mb-3\">");
		out.append("                      <label for=\"renewPassword\" class=\"col-md-4 col-lg-2 col-form-label\">Nhập lại mật khẩu mới</label>");
		out.append("                      <div class=\"col-md-8 col-lg-10\">");
		out.append("                        <input name=\"renewPassword\" type=\"password\" class=\"form-control\" id=\"renewPassword\">");
		out.append("                      </div>");
		out.append("                    </div>");
		out.append("");
		out.append("                    <div class=\"text-center\">");
		out.append("                      <button type=\"submit\" class=\"btn btn-primary\">Đổi mật khẩu</button>");
		out.append("                    </div>");
		out.append("                  </form><!-- End Change Password Form -->");
		out.append("");
		out.append("                </div>");
		
		
		out.append("              </div><!-- End Bordered Tabs -->");
		out.append("");
		out.append("            </div>");
		out.append("          </div>");
		out.append("");
		out.append("        </div>");
		out.append("      </div>");
		out.append("    </section>");
		out.append("");
		out.append("  </main><!-- End #main -->");
		out.append("");
		out.append("  <!-- ======= Footer ======= -->");
		out.append("  <footer id=\"footer\" class=\"footer\">");
		out.append("    <div class=\"copyright\">");
		out.append("      &copy; Copyright <strong><span>TravelVN</span></strong>. All Rights Reserved");
		out.append("    </div>");
		out.append("    <div class=\"credits\">");
		out.append("      <!-- All the links in the footer should remain intact. -->");
		out.append("      <!-- You can delete the links only if you purchased the pro version. -->");
		out.append("      <!-- Licensing information: https://bootstrapmade.com/license/ -->");
		out.append("      <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/ -->");
		out.append("      <!-- Designed by <a href=\"https://bootstrapmade.com/\">BootstrapMade</a> -->");
		out.append("    </div>");
		out.append("  </footer><!-- End Footer -->");
		out.append("");
		out.append("  <a href=\"#\" class=\"back-to-top d-flex align-items-center justify-content-center\"><i");
		out.append("      class=\"bi bi-arrow-up-short\"></i></a>");
		out.append("");
		out.append("  <!-- Vendor JS Files -->");
		out.append("  <script src=\"/adv/assets/vendor/apexcharts/apexcharts.min.js\"></script>");
		out.append("  <script src=\"/adv/assets/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>");
		out.append("  <script src=\"/adv/assets/vendor/chart.js/chart.umd.js\"></script>");
		out.append("  <script src=\"/adv/assets/vendor/echarts/echarts.min.js\"></script>");
		out.append("  <script src=\"/adv/assets/vendor/quill/quill.js\"></script>");
		out.append("  <script src=\"/adv/assets/vendor/simple-datatables/simple-datatables.js\"></script>");
		out.append("  <script src=\"/adv/assets/vendor/tinymce/tinymce.min.js\"></script>");
		out.append("  <script src=\"/adv/assets/vendor/php-email-form/validate.js\"></script>");
		out.append("");
		out.append("  <!-- Template Main JS File -->");
		out.append("  <script src=\"/adv/assets/js/main.js\"></script>");
		out.append("");
		out.append("</body>");
		out.append("");
		out.append("</html>");
	}	
}
