package ads.ad;

import java.io.IOException;
import java.io.PrintWriter;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Locale;

import ads.objects.TourGuide;
import ads.objects.TourOperator;
import ads.user.TourGuideFunction;
import ads.user.TourGuideFunctionImpl;
import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import jakarta.servlet.http.HttpSession;

@WebServlet("/ad-tourguide-management")
public class TourGuideManagementServlet extends HttpServlet {
	private TourGuideFunction tourGuideFunction = new TourGuideFunctionImpl();

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Override
	protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
		resp.setCharacterEncoding("UTF-8");
		resp.setContentType("text/html; charset=UTF-8");
		
		HttpSession session = req.getSession(false);
		if (session == null || session.getAttribute("username") == null) {
			resp.sendRedirect(req.getContextPath() + "/ad-login");
			return;
		}

		String username = (String) session.getAttribute("username");
		
		ArrayList<TourGuide> tourGuides = tourGuideFunction.getFirst100TourGuide();
		
		PrintWriter out = resp.getWriter();
		
		out.append("<!DOCTYPE html>");
		out.append("<html lang=\"en\">");
		out.append("");
		out.append("<head>");
		out.append("  <meta charset=\"utf-8\">");
		out.append("  <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">");
		out.append("");
		out.append("  <title>TravelVN - Quản lý hướng dẫn viên du lịch</title>");
		out.append("  <meta content=\"\" name=\"description\">");
		out.append("  <meta content=\"\" name=\"keywords\">");
		out.append("");
		out.append("  <!-- Favicons -->");
		out.append("  <link href=\"assets/img/Logo.svg\" rel=\"icon\">");
		out.append("  <link href=\"assets/img/apple-touch-icon.png\" rel=\"apple-touch-icon\">");
		out.append("");
		out.append("  <!-- Google Fonts -->");
		out.append("  <link href=\"https://fonts.gstatic.com\" rel=\"preconnect\">");
		out.append("  <link");
		out.append("    href=\"https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i\"");
		out.append("    rel=\"stylesheet\">");
		out.append("");
		out.append("  <!-- Vendor CSS Files -->");
		out.append("  <link href=\"assets/vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">");
		out.append("  <link href=\"assets/vendor/bootstrap-icons/bootstrap-icons.css\" rel=\"stylesheet\">");
		out.append("  <link href=\"assets/vendor/boxicons/css/boxicons.min.css\" rel=\"stylesheet\">");
		out.append("  <link href=\"assets/vendor/quill/quill.snow.css\" rel=\"stylesheet\">");
		out.append("  <link href=\"assets/vendor/quill/quill.bubble.css\" rel=\"stylesheet\">");
		out.append("  <link href=\"assets/vendor/remixicon/remixicon.css\" rel=\"stylesheet\">");
		out.append("  <link href=\"assets/vendor/simple-datatables/style.css\" rel=\"stylesheet\">");
		out.append("");
		out.append("  <!-- Template Main CSS File -->");
		out.append("  <link href=\"assets/css/style.css\" rel=\"stylesheet\">");
		out.append("</head>");
		out.append("");
		out.append("<body>");
		out.append("");
		out.append("    <!-- ======= Header ======= -->");
		out.append("    <header id=\"header\" class=\"header fixed-top d-flex align-items-center\">");
		out.append("");
		out.append("        <div class=\"d-flex align-items-center justify-content-between\">");
		out.append("            <a href=\"index.html\" class=\"logo d-flex align-items-center\">");
		out.append("                <img src=\"assets/img/Logo.svg\" alt=\"\">");
		out.append("                <span class=\"d-none d-lg-block\">TravelVN</span>");
		out.append("            </a>");
		out.append("            <i class=\"bi bi-list toggle-sidebar-btn\"></i>");
		out.append("        </div><!-- End Logo -->");
		out.append("");
		out.append("        <nav class=\"header-nav ms-auto\">");
		out.append("            <ul class=\"d-flex align-items-center\">");
		out.append("");
		out.append("                <li class=\"nav-item dropdown pe-3\">");
		out.append("");
		out.append("                    <a class=\"nav-link nav-profile d-flex align-items-center pe-0\" href=\"#\" data-bs-toggle=\"dropdown\">");
		out.append("                        <span class=\"d-none d-md-block dropdown-toggle ps-2\">" + username + "</span>");
		out.append("                    </a>");
		out.append("");
		out.append("                    <ul class=\"dropdown-menu dropdown-menu-end dropdown-menu-arrow profile\">");
		out.append("                        <li class=\"dropdown-header\">");
		out.append("                            <h6>" + username + "</h6>");
		out.append("                            <span>Người quản lý</span>");
		out.append("                        </li>");
		out.append("                        <li>");
		out.append("                            <hr class=\"dropdown-divider\">");
		out.append("                        </li>");
		out.append("");
		out.append("                        <li>");
		out.append("                            <a class=\"dropdown-item d-flex align-items-center\" href=\"" + req.getContextPath() + "/ad-profile-management\">");
		out.append("                                <i class=\"bi bi-person\"></i>");
		out.append("                                <span>Hồ sơ của tôi</span>");
		out.append("                            </a>");
		out.append("                        </li>");
		out.append("                        <li>");
		out.append("                            <hr class=\"dropdown-divider\">");
		out.append("                        </li>");
		out.append("");
		out.append("                        <li>");
		out.append("                            <a class=\"dropdown-item d-flex align-items-center\" href=\"" + req.getContextPath() + "/ad-logout\">");
		out.append("                                <i class=\"bi bi-box-arrow-right\"></i>");
		out.append("                                <span>Đăng xuất</span>");
		out.append("                            </a>");
		out.append("                        </li>");
		out.append("");
		out.append("                    </ul><!-- End Profile Dropdown Items -->");
		out.append("                </li><!-- End Profile Nav -->");
		out.append("");
		out.append("            </ul>");
		out.append("        </nav><!-- End Icons Navigation -->");
		out.append("");
		out.append("    </header><!-- End Header -->");
		out.append("");
		out.append("  <!-- ======= Sidebar ======= -->");
		out.append("  <aside id=\"sidebar\" class=\"sidebar\">");
		out.append("");
		out.append("    <ul class=\"sidebar-nav\" id=\"sidebar-nav\">");
		out.append("");
		out.append("      <!-- Dashboard Nav -->");
		out.append("      <li class=\"nav-item\">");
		out.append("        <a class=\"nav-link collapsed\" href=\"" + req.getContextPath() + "/ad-dashboard\">");
		out.append("          <i class=\"bx bx-category\"></i>");
		out.append("          <span>Tổng quan</span>");
		out.append("        </a>");
		out.append("      </li>");
		out.append("      <!-- End Dashboard Nav -->");
		out.append("");
		out.append("      <!-- Account Management Nav -->");
		out.append("      <li class=\"nav-item\">");
		out.append("        <a class=\"nav-link collapsed\" href=\"" + req.getContextPath() + "/ad-account-management\">");
		out.append("          <i class=\"bx bx-user-circle\"></i>");
		out.append("          <span>Quản lý tài khoản</span>");
		out.append("        </a>");
		out.append("      </li>");
		out.append("      <!-- End Account Management Nav -->");
		out.append("");
		out.append("      <!-- Staff Management Nav -->");
		out.append("      <li class=\"nav-item\">");
		out.append("        <a class=\"nav-link\" data-bs-target=\"#staff-management-nav\" data-bs-toggle=\"collapse\" href=\"#\">");
		out.append("          <i class=\"bx bx-user\"></i><span>Quản lý nhân viên</span><i class=\"bi bi-chevron-down ms-auto\"></i>");
		out.append("        </a>");
		out.append("        <ul id=\"staff-management-nav\" class=\"nav-content collapse show\" data-bs-parent=\"#sidebar-nav\">");
		out.append("          <li>");
		out.append("            <a href=\"" + req.getContextPath() + "/ad-touroperator-management\">");
		out.append("              <i class=\"bi bi-circle\"></i><span style=\"font-size: 12px;\">Điều hành Tour</span>");
		out.append("            </a>");
		out.append("          </li>");
		out.append("          <li>");
		out.append("            <a href=\"" + req.getContextPath() + "/ad-tourguide-management\" class=\"active\">");
		out.append("              <i class=\"bi bi-circle\"></i><span style=\"font-size: 12px;\">Hướng dẫn viên</span>");
		out.append("            </a>");
		out.append("          </li>");
		out.append("        </ul>");
		out.append("      </li>");
		out.append("      <!-- End Staff Management Nav -->");
		out.append("");
		out.append("      <!-- Customer Management Nav -->");
		out.append("      <li class=\"nav-item\">");
		out.append("        <a class=\"nav-link collapsed\" href=\"" + req.getContextPath() + "/ad-customer-management\">");
		out.append("          <i class=\"bx bx-group\"></i>");
		out.append("          <span>Quản lý khách hàng</span>");
		out.append("        </a>");
		out.append("      </li>");
		out.append("      <!-- End Customer Management Nav -->");
		out.append("");
		out.append("      <!-- Tour Management Nav -->");
		out.append("      <li class=\"nav-item\">");
		out.append("        <a class=\"nav-link collapsed\" href=\"" + req.getContextPath() + "/ad-tour-management\">");
		out.append("          <i class=\"bx bx-food-menu\"></i>");
		out.append("          <span>Quản lý Tour</span>");
		out.append("        </a>");
		out.append("      </li>");
		out.append("      <!-- End Tour Management Nav -->");
		out.append("");
		out.append("      <!-- Review Management Nav -->");
		out.append("      <li class=\"nav-item\">");
		out.append("        <a class=\"nav-link collapsed\" href=\"" + req.getContextPath() + "/ad-tourrating-management\">");
		out.append("          <i class=\"bx bx-message-square-detail\"></i>");
		out.append("          <span>Duyệt đánh giá</span>");
		out.append("        </a>");
		out.append("      </li>");
		out.append("      <!-- End Review Management Nav -->");
		out.append("    </ul>");
		out.append("");
		out.append("  </aside><!-- End Sidebar-->");
		out.append("");
		out.append("  <main id=\"main\" class=\"main\">");
		out.append("");
		out.append("    <div class=\"pagetitle d-flex\">");
		out.append("      <h1>Quản lý hướng dẫn viên du lịch</h1>");
		out.append("      <nav class=\"ms-auto\">");
		out.append("        <ol class=\"breadcrumb\">");
		out.append("          <li class=\"breadcrumb-item active\">Quản lý hướng dẫn viên du lịch</li>");
		out.append("        </ol>");
		out.append("      </nav>");
		out.append("    </div><!-- End Page Title -->");
		out.append("");
		out.append("    <section class=\"section\">");
		out.append("      <div class=\"row\">");
		out.append("        <div class=\"col-lg-12\">");
		out.append("");
		out.append("          <div class=\"card\">");
		out.append("            <div class=\"card-body\">");
		out.append("              <div class=\"d-flex justify-content-between mt-4 mb-3\">");
		out.append("                <div class=\"d-flex align-items-center\">");
		out.append("                  <select id=\"recordCount\" class=\"p-1 ps-2\">");
		out.append("                    <option value=\"5\">5</option>");
		out.append("                    <option value=\"10\" selected>10</option>");
		out.append("                    <option value=\"20\">20</option>");
		out.append("                    <option value=\"all\">Tất cả</option>");
		out.append("                  </select>");
		out.append("                  <label for=\"recordCount\" class=\"ms-2 me-4\">bản ghi / trang</label>");
		out.append("                  <div>");
		out.append("                    <input type=\"text\" id=\"searchInput\" class=\"p-1 ps-2\" placeholder=\"Tìm kiếm...\" />");
		out.append("                  </div>");
		out.append("                </div>");
		out.append("                <button type=\"button\" class=\"btn btn-success btn-sm\" data-bs-toggle=\"modal\"");
		out.append("                  data-bs-target=\"#addNewModal\"><i class=\"bx bx-user-plus me-1\"></i>Thêm mới</button>");
		out.append("              </div>");
		out.append("");
		out.append("              <!-- Table with stripped rows -->");
		out.append("              <table class=\"table table-hover\" id=\"myTable\">");
		out.append("                <thead>");
		out.append("                  <tr>");
		out.append("                    <th class=\"text-center\">#</th>");
		out.append("                    <th class=\"text-center\">ID</th>");
		out.append("                    <th>Họ và tên</th>");
		out.append("                    <th data-type=\"date\" data-format=\"DD/MM/YYYY\">Ngày sinh</th>");
		out.append("                    <th>Giới tính</th>");
		out.append("                    <th>Số điện thoại</th>");
		out.append("                    <th>CCCD</th>");
		out.append("                    <th>Lương</th>");
		out.append("                    <th class=\"text-center\">Hành động</th>");
		out.append("                  </tr>");
		out.append("                </thead>");
		out.append("                <tbody>");
		
		for (TourGuide tourGuide : tourGuides) {
			String fullName = tourGuide.getLastname() + " " + tourGuide.getFirstname();
			String gender = tourGuide.getGender() ? "Nam" : "Nữ";
			// Định dạng ngày
			DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
			// Định dạng tiền
			DecimalFormatSymbols symbols = new DecimalFormatSymbols(Locale.getDefault());
	        symbols.setGroupingSeparator('.');
			DecimalFormat salaryFormatter = new DecimalFormat("#,##0 đ", symbols);
			// Lương
			String salaryFormat = salaryFormatter.format(tourGuide.getSalary());
			
			out.append("                  <tr>");
			out.append("                    <th class=\"text-center\"></th>");
			out.append("                    <td class=\"text-center\">" + tourGuide.getId() + "</td>");
			out.append("                    <td>" + fullName + "</td>");
			out.append("                    <td>" + tourGuide.getDateOfBirth().format(formatter) + "</td>");
			out.append("                    <td>" + gender + "</td>");
			out.append("                    <td>" + tourGuide.getPhoneNumber() + "</td>");
			out.append("                    <td>" + tourGuide.getCitizenId() + "</td>");
			out.append("                    <td>" + salaryFormat + "</td>");
			out.append("                    <td class=\"text-center\">");
			out.append("                      <button type=\"button\" class=\"btn btn-outline-primary btn-sm\" data-bs-toggle=\"modal\" data-bs-target=\"#moreInforModal-" + tourGuide.getId() + "\"><i class=\"ri-more-fill\"></i></button>");
			out.append("                      <button type=\"button\" class=\"btn btn-primary btn-sm\" data-bs-toggle=\"modal\" data-bs-target=\"#changeInforModal-" + tourGuide.getId() + "\"><i class=\"bx bxs-pencil\"></i></button>");
			out.append("                      <button type=\"button\" class=\"btn btn-danger btn-sm\" data-bs-toggle=\"modal\" data-bs-target=\"#confirmDeleteModal-" + tourGuide.getId() + "\"><i class=\"bx bx-trash\"></i></button>");
			out.append("                    </td>");
			out.append("                  </tr>");
			
			// Modal xem chi tiết cho từng Tour Guide
			out.append("    <!-- Modal Xem Chi Tiết -->");
			out.append("    <div class=\"modal fade\" id=\"moreInforModal-" + tourGuide.getId() + "\" tabindex=\"-1\" aria-labelledby=\"moreInforModalLabel\" aria-hidden=\"true\">");
			out.append("      <div class=\"modal-dialog modal-lg\">");
			out.append("        <div class=\"modal-content\">");
			out.append("          <div class=\"modal-header text-bg-primary\">");
			out.append("            <h5 class=\"modal-title fw-bold\" id=\"moreInforModalLabel\">Thông tin chi tiết hướng dẫn viên du lịch - " + tourGuide.getId() + "</h5>");
			out.append("            <button type=\"button\" class=\"btn-close fs-2\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>");
			out.append("          </div>");
			out.append("          <div class=\"modal-body\">");
			out.append("            <div class=\"row\">");
			out.append("                <div class=\"col-md-6 mb-2\">");
			out.append("                  <label for=\"lastName\" class=\"form-label\">Họ</label>");
			out.append("                  <input type=\"text\" class=\"form-control\" id=\"lastName\" name=\"lastName\" value=\"" + tourGuide.getLastname() + "\" disabled>");
			out.append("                </div>");
			out.append("                <div class=\"col-md-6 mb-2\">");
			out.append("                  <label for=\"firstName\" class=\"form-label\">Tên</label>");
			out.append("                  <input type=\"text\" class=\"form-control\" id=\"firstName\" name=\"firstName\" value=\"" + tourGuide.getFirstname() + "\" disabled>");
			out.append("                </div>");
			out.append("              </div>");
			out.append("");
			out.append("              <div class=\"row\">");
			out.append("                <div class=\"col-md-6 mb-2\">");
			out.append("                  <label for=\"dob\" class=\"form-label\">Ngày sinh</label>");
			out.append("                  <input type=\"date\" class=\"form-control\" id=\"dob\" name=\"dob\" value=\"" + tourGuide.getDateOfBirth() + "\" disabled>");
			out.append("                </div>");
			out.append("                <div class=\"col-md-6 mb-2\">");
			out.append("                  <label for=\"gender\" class=\"form-label\">Giới tính</label>");
			out.append("                  <input type=\"text\" class=\"form-control\" id=\"gender\" name=\"gender\" value=\"" + gender + "\" disabled>");
			out.append("                </div>");
			out.append("              </div>");
			out.append("");
			out.append("              <div class=\"row\">");
			out.append("                <div class=\"col-md-6 mb-2\">");
			out.append("                  <label for=\"phoneNumber\" class=\"form-label\">Số điện thoại</label>");
			out.append("                  <input type=\"text\" class=\"form-control\" id=\"phoneNumber\" name=\"phoneNumber\" value=\"" + tourGuide.getPhoneNumber() + "\" disabled>");
			out.append("                </div>");
			out.append("                <div class=\"col-md-6 mb-2\">");
			out.append("                  <label for=\"citizenId\" class=\"form-label\">CCCD</label>");
			out.append("                  <input type=\"text\" class=\"form-control\" id=\"citizenId\" name=\"citizenId\" value=\"" + tourGuide.getCitizenId() + "\" disabled>");
			out.append("                </div>");
			out.append("              </div>");
			out.append("");
			out.append("              <div class=\"row\">");
			out.append("                <div class=\"col-md-6 mb-2\">");
			out.append("                  <label for=\"cardId\" class=\"form-label\">Mã thẻ hướng dẫn</label>");
			out.append("                  <input type=\"text\" class=\"form-control\" id=\"cardId\" name=\"cardId\" value=\"" + tourGuide.getCardId() + "\" disabled>");
			out.append("                </div>");
			out.append("                <div class=\"col-md-6 mb-2\">");
			out.append("                  <label for=\"language\" class=\"form-label\">Ngôn ngữ</label>");
			out.append("                  <input type=\"text\" class=\"form-control\" id=\"language\" name=\"language\" value=\"" + tourGuide.getLanguage() + "\" disabled>");
			out.append("                </div>");
			out.append("              </div>");
			out.append("");
			out.append("              <div class=\"row\">");
			out.append("                <div class=\"col-md-6 mb-2\">");
			out.append("                  <label for=\"hometown\" class=\"form-label\">Quê quán</label>");
			out.append("                  <input type=\"text\" class=\"form-control\" id=\"hometown\" name=\"hometown\" value=\"" + tourGuide.getHometown() + "\" disabled>");
			out.append("                </div>");
			out.append("                <div class=\"col-md-6 mb-2\">");
			out.append("                  <label for=\"address\" class=\"form-label\">Địa chỉ</label>");
			out.append("                  <input type=\"text\" class=\"form-control\" id=\"address\" name=\"address\" value=\"" + tourGuide.getAddress() + "\" disabled>");
			out.append("                </div>");
			out.append("              </div>");
			out.append("");
			out.append("              <div class=\"row mb-2\">");
			out.append("                <div class=\"col-md-4 mb-2\">");
			out.append("                  <label for=\"startDate\" class=\"form-label\">Ngày bắt đầu hợp đồng</label>");
			out.append("                  <input type=\"date\" class=\"form-control\" id=\"startDate\" name=\"startDate\" value=\"" + tourGuide.getStartDate() + "\" disabled>");
			out.append("                </div>");
			out.append("                <div class=\"col-md-4 mb-2\">");
			out.append("                  <label for=\"endDate\" class=\"form-label\">Ngày kết thúc hợp đồng</label>");
			out.append("                  <input type=\"date\" class=\"form-control\" id=\"endDate\" name=\"endDate\" value=\"" + tourGuide.getEndDate() + "\" disabled>");
			out.append("                </div>");
			out.append("                <div class=\"col-md-4 mb-2\">");
			out.append("                  <label for=\"salary\" class=\"form-label\">Lương</label>");
			out.append("                  <input type=\"text\" class=\"form-control\" id=\"salary\" name=\"salary\" value=\"" + salaryFormat + "\" disabled>");
			out.append("                </div>");
			out.append("              </div>");
			out.append("");
			out.append("            <div class=\"w-100 d-flex justify-content-center\">");
			out.append("              <button type=\"button\" class=\"btn btn-primary w-50 me-1\" data-bs-toggle=\"modal\" data-bs-target=\"#changeInforModal-" + tourGuide.getId() + "\"><i class=\"bx bxs-pencil me-2\"></i>Sửa</button>");
			out.append("              <button type=\"button\" class=\"btn btn-danger w-50 ms-1\" data-bs-toggle=\"modal\" data-bs-target=\"#confirmDeleteModal-" + tourGuide.getId() + "\"><i class=\"bx bx-trash me-2\"></i>Xóa</button>");
			out.append("            </div>");
			out.append("          </div>");
			out.append("        </div>");
			out.append("      </div>");
			out.append("    </div>");
			
			// Modal sửa thông tin cho từng Tour Guide
			out.append("    <!-- Modal Sửa Thông Tin -->");
			out.append("    <div class=\"modal fade\" id=\"changeInforModal-" + tourGuide.getId() + "\" tabindex=\"-1\" aria-labelledby=\"changeInforModalLabel\"");
			out.append("      aria-hidden=\"true\">");
			out.append("      <div class=\"modal-dialog modal-lg\">");
			out.append("        <div class=\"modal-content\">");
			out.append("          <div class=\"modal-header text-bg-primary\">");
			out.append("            <h5 class=\"modal-title fw-bold\" id=\"changeInforModalLabel\">Sửa thông tin hướng dẫn viên du lịch - " + tourGuide.getId() + "</h5>");
			out.append("            <button type=\"button\" class=\"btn-close fs-2\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>");
			out.append("          </div>");
			out.append("          <div class=\"modal-body\">");
			out.append("            <form id=\"formChangeInfor\" action=\"" + req.getContextPath() + "/ad-tourguide-management/update\" method=\"POST\">");
			out.append("              <input type=\"hidden\" class=\"form-control\" id=\"id\" name=\"id\" value=\"" + tourGuide.getId() + "\">");
			out.append("              <div class=\"row\">");
			out.append("                <div class=\"col-md-6 mb-2\">");
			out.append("                  <label for=\"lastName\" class=\"form-label\">Họ</label>");
			out.append("                  <input type=\"text\" class=\"form-control\" id=\"lastName\" name=\"lastName\" value=\"" + tourGuide.getLastname() + "\" required>");
			out.append("                </div>");
			out.append("                <div class=\"col-md-6 mb-2\">");
			out.append("                  <label for=\"firstName\" class=\"form-label\">Tên</label>");
			out.append("                  <input type=\"text\" class=\"form-control\" id=\"firstName\" name=\"firstName\" value=\"" + tourGuide.getFirstname() + "\" required>");
			out.append("                </div>");
			out.append("              </div>");
			out.append("");
			out.append("              <div class=\"row\">");
			out.append("                <div class=\"col-md-6 mb-2\">");
			out.append("                  <label for=\"dob\" class=\"form-label\">Ngày sinh</label>");
			out.append("                  <input type=\"date\" class=\"form-control\" id=\"dob\" name=\"dob\" value=\"" + tourGuide.getDateOfBirth() + "\" required>");
			out.append("                </div>");
			out.append("                <div class=\"col-md-6 mb-2\">");
			out.append("                  <label for=\"gender\" class=\"form-label\">Giới tính</label>");
			out.append("                  <select class=\"form-select\" id=\"gender\" name=\"gender\" value=\"\" required>");
			out.append("                    <option value=\"male\" " + (gender.equals("Nam") ? "selected" : "") + ">Nam</option>");
			out.append("                    <option value=\"female\" " + (gender.equals("Nữ") ? "selected" : "") + ">Nữ</option>");
			out.append("                  </select>");
			out.append("                </div>");
			out.append("              </div>");
			out.append("");
			out.append("              <div class=\"row\">");
			out.append("                <div class=\"col-md-6 mb-2\">");
			out.append("                  <label for=\"phoneNumber\" class=\"form-label\">Số điện thoại</label>");
			out.append("                  <input type=\"text\" minlength=\"10\" maxlength=\"10\" class=\"form-control\" id=\"phoneNumber\" name=\"phoneNumber\" value=\"" + tourGuide.getPhoneNumber() + "\" required>");
			out.append("                </div>");
			out.append("                <div class=\"col-md-6 mb-2\">");
			out.append("                  <label for=\"citizenId\" class=\"form-label\">CCCD</label>");
			out.append("                  <input type=\"text\" minlength=\"12\" maxlength=\"12\" class=\"form-control\" id=\"citizenId\" name=\"citizenId\" value=\"" + tourGuide.getCitizenId() + "\" required>");
			out.append("                </div>");
			out.append("              </div>");
			out.append("");
			out.append("              <div class=\"row\">");
			out.append("                <div class=\"col-md-6 mb-2\">");
			out.append("                  <label for=\"cardId\" class=\"form-label\">Mã thẻ hướng dẫn</label>");
			out.append("                  <input type=\"text\" minlength=\"12\" maxlength=\"12\" class=\"form-control\" id=\"cardId\" name=\"cardId\" value=\"" + tourGuide.getCardId() + "\" required>");
			out.append("                </div>");
			out.append("                <div class=\"col-md-6 mb-2\">");
			out.append("                  <label for=\"language\" class=\"form-label\">Ngôn ngữ</label>");
			out.append("                  <input type=\"text\" class=\"form-control\" id=\"language\" name=\"language\" value=\"" + tourGuide.getLanguage() + "\" required>");
			out.append("                </div>");
			out.append("              </div>");
			out.append("");
			out.append("              <div class=\"row\">");
			out.append("                <div class=\"col-md-6 mb-2\">");
			out.append("                  <label for=\"hometown\" class=\"form-label\">Quê quán</label>");
			out.append("                  <input type=\"text\" class=\"form-control\" id=\"hometown\" name=\"hometown\" value=\"" + tourGuide.getHometown() + "\" required>");
			out.append("                </div>");
			out.append("                <div class=\"col-md-6 mb-2\">");
			out.append("                  <label for=\"address\" class=\"form-label\">Địa chỉ</label>");
			out.append("                  <input type=\"text\" class=\"form-control\" id=\"address\" name=\"address\" value=\"" + tourGuide.getAddress() + "\" required>");
			out.append("                </div>");
			out.append("              </div>");
			out.append("");
			out.append("              <div class=\"row mb-2\">");
			out.append("                <div class=\"col-md-4 mb-2\">");
			out.append("                  <label for=\"startDate\" class=\"form-label\">Ngày bắt đầu hợp đồng</label>");
			out.append("                  <input type=\"date\" class=\"form-control\" id=\"startDate\" name=\"startDate\" value=\"" + tourGuide.getStartDate() + "\" required>");
			out.append("                </div>");
			out.append("                <div class=\"col-md-4 mb-2\">");
			out.append("                  <label for=\"endDate\" class=\"form-label\">Ngày kết thúc hợp đồng</label>");
			out.append("                  <input type=\"date\" class=\"form-control\" id=\"endDate\" name=\"endDate\" value=\"" + tourGuide.getEndDate() + "\" required>");
			out.append("                </div>");
			out.append("                <div class=\"col-md-4 mb-2\">");
			out.append("                  <label for=\"salary\" class=\"form-label\">Lương</label>");
			out.append("                  <input type=\"text\" class=\"form-control\" id=\"salary\" name=\"salary\" value=\"" + tourGuide.getSalary() + "\" required>");
			out.append("                </div>");
			out.append("              </div>");
			out.append("");
			out.append("              <button type=\"submit\" class=\"btn btn-primary w-100\">Lưu thay đổi</button>");
			out.append("            </form>");
			out.append("          </div>");
			out.append("        </div>");
			out.append("      </div>");
			out.append("    </div>");
			
			// Modal xác nhận xóa cho từng Tour Guide
			out.append("    <!-- Modal Xác Nhận Xóa -->");
			out.append("    <div class=\"modal fade\" id=\"confirmDeleteModal-" + tourGuide.getId() + "\" tabindex=\"-1\" aria-labelledby=\"confirmDeleteModalLabel\"");
			out.append("      aria-hidden=\"true\">");
			out.append("      <div class=\"modal-dialog\">");
			out.append("        <div class=\"modal-content\">");
			out.append("          <div class=\"modal-header text-bg-danger\">");
			out.append("            <h5 class=\"modal-title text-light fw-bold\" id=\"confirmDeleteModalLabel\">Xác nhận xóa</h5>");
			out.append("            <button type=\"button\" class=\"btn-close fs-2\" data-bs-dismiss=\"modal\" aria-label=\"Đóng\"></button>");
			out.append("          </div>");
			out.append("          <div class=\"modal-body\">");
			out.append("            Bạn có chắc chắn muốn xóa <strong>" + fullName + "</strong> không?");
			out.append("          </div>");
			out.append("          <div class=\"modal-footer\">");
			out.append("            <form method=\"post\" action=\"" + req.getContextPath() + "/ad-tourguide-management/delete\">");
			out.append("               <input type=\"hidden\" name=\"tourGuideId\" value=\"" + tourGuide.getId() + "\">");
			out.append("               <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">Hủy</button>");
			out.append("               <button type=\"submit\" class=\"btn btn-danger\">Xóa</button>");
			out.append("             </form>");
			out.append("          </div>");
			out.append("        </div>");
			out.append("      </div>");
			out.append("    </div>");
		}
		
		out.append("                </tbody>");
		out.append("              </table>");
		out.append("              <!-- End Table with stripped rows -->");
		out.append("");
		out.append("              <div class=\"d-flex align-items-center justify-content-between\">");
		out.append("                <span id=\"recordInfo\"></span>");
		out.append("                <div id=\"pagination\"></div>");
		out.append("              </div>");
		out.append("");
		out.append("");
		out.append("            </div>");
		out.append("          </div>");
		out.append("");
		out.append("        </div>");
		out.append("      </div>");
		out.append("    </section>");
		out.append("");
		
		// Modal thêm mới Tour Guide
		out.append("    <!-- Modal Thêm Mới -->");
		out.append("    <div class=\"modal fade\" id=\"addNewModal\" tabindex=\"-1\" aria-labelledby=\"addNewModalLabel\" aria-hidden=\"true\">");
		out.append("      <div class=\"modal-dialog modal-lg\">");
		out.append("        <div class=\"modal-content\">");
		out.append("          <div class=\"modal-header text-bg-success\">");
		out.append("            <h5 class=\"modal-title fw-bold \" id=\"addNewModalLabel\">Thêm mới hướng dẫn viên du lịch</h5>");
		out.append("            <button type=\"button\" class=\"btn-close fs-2\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>");
		out.append("          </div>");
		out.append("          <div class=\"modal-body\">");
		out.append("            <form id=\"formAddNew\" action=\"" + req.getContextPath() + "/ad-tourguide-management/add\" method=\"POST\">");
		out.append("              <div class=\"row\">");
		out.append("                <div class=\"col-md-6 mb-2\">");
		out.append("                  <label for=\"lastName\" class=\"form-label\">Họ</label>");
		out.append("                  <input type=\"text\" class=\"form-control\" id=\"lastName\" name=\"lastName\" required>");
		out.append("                </div>");
		out.append("                <div class=\"col-md-6 mb-2\">");
		out.append("                  <label for=\"firstName\" class=\"form-label\">Tên</label>");
		out.append("                  <input type=\"text\" class=\"form-control\" id=\"firstName\" name=\"firstName\" required>");
		out.append("                </div>");
		out.append("              </div>");
		out.append("");
		out.append("              <div class=\"row\">");
		out.append("                <div class=\"col-md-6 mb-2\">");
		out.append("                  <label for=\"dob\" class=\"form-label\">Ngày sinh</label>");
		out.append("                  <input type=\"date\" class=\"form-control\" id=\"dob\" name=\"dob\" required>");
		out.append("                </div>");
		out.append("                <div class=\"col-md-6 mb-2\">");
		out.append("                  <label for=\"gender\" class=\"form-label\">Giới tính</label>");
		out.append("                  <select class=\"form-select\" id=\"gender\" name=\"gender\" required>");
		out.append("                    <option value=\"Male\">Nam</option>");
		out.append("                    <option value=\"Female\">Nữ</option>");
		out.append("                  </select>");
		out.append("                </div>");
		out.append("              </div>");
		out.append("");
		out.append("              <div class=\"row\">");
		out.append("                <div class=\"col-md-6 mb-2\">");
		out.append("                  <label for=\"phoneNumber\" class=\"form-label\">Số điện thoại</label>");
		out.append("                  <input type=\"text\" pattern=\"\\d{10}\" title=\"Số điện thoại 10 chữ số\" class=\"form-control\" id=\"phoneNumber\" name=\"phoneNumber\" required>");
		out.append("                </div>");
		out.append("                <div class=\"col-md-6 mb-2\">");
		out.append("                  <label for=\"citizenId\" class=\"form-label\">CCCD</label>");
		out.append("                  <input type=\"text\" pattern=\"\\d{12}\" title=\"CCCD 12 chữ số\" class=\"form-control\" id=\"citizenId\" name=\"citizenId\" required>");
		out.append("                </div>");
		out.append("              </div>");
		out.append("");
		out.append("              <div class=\"row\">");
		out.append("                <div class=\"col-md-6 mb-2\">");
		out.append("                  <label for=\"cardId\" class=\"form-label\">Mã thẻ hướng dẫn</label>");
		out.append("                  <input type=\"text\" pattern=\"\\d{12}\" title=\"Mã thẻ hướng dẫn 12 chữ số\" class=\"form-control\" id=\"cardId\" name=\"cardId\" required>");
		out.append("                </div>");
		out.append("                <div class=\"col-md-6 mb-2\">");
		out.append("                  <label for=\"language\" class=\"form-label\">Ngôn ngữ</label>");
		out.append("                  <input type=\"text\" class=\"form-control\" id=\"language\" name=\"language\" required>");
		out.append("                </div>");
		out.append("              </div>");
		out.append("");
		out.append("              <div class=\"row\">");
		out.append("                <div class=\"col-md-6 mb-2\">");
		out.append("                  <label for=\"hometown\" class=\"form-label\">Quê quán</label>");
		out.append("                  <input type=\"text\" class=\"form-control\" id=\"hometown\" name=\"hometown\" required>");
		out.append("                </div>");
		out.append("                <div class=\"col-md-6 mb-2\">");
		out.append("                  <label for=\"address\" class=\"form-label\">Địa chỉ</label>");
		out.append("                  <input type=\"text\" class=\"form-control\" id=\"address\" name=\"address\" required>");
		out.append("                </div>");
		out.append("              </div>");
		out.append("");
		out.append("              <div class=\"row mb-2\">");
		out.append("                <div class=\"col-md-4 mb-2\">");
		out.append("                  <label for=\"startDate\" class=\"form-label\">Ngày bắt đầu hợp đồng</label>");
		out.append("                  <input type=\"date\" class=\"form-control\" id=\"startDate\" name=\"startDate\" required>");
		out.append("                </div>");
		out.append("                <div class=\"col-md-4 mb-2\">");
		out.append("                  <label for=\"endDate\" class=\"form-label\">Ngày kết thúc hợp đồng</label>");
		out.append("                  <input type=\"date\" class=\"form-control\" id=\"endDate\" name=\"endDate\" required>");
		out.append("                </div>");
		out.append("                <div class=\"col-md-4 mb-2\">");
		out.append("                  <label for=\"salary\" class=\"form-label\">Lương</label>");
		out.append("                  <input type=\"text\" class=\"form-control\" id=\"salary\" name=\"salary\" required>");
		out.append("                </div>");
		out.append("              </div>");
		out.append("");
		out.append("              <button type=\"submit\" class=\"btn btn-success w-100\">Lưu</button>");
		out.append("            </form>");
		out.append("          </div>");
		out.append("        </div>");
		out.append("      </div>");
		out.append("    </div>");
		out.append("");
		
//		out.append("    <!-- Modal Xem Chi Tiết -->");
//		out.append("    <div class=\"modal fade\" id=\"moreInforModal\" tabindex=\"-1\" aria-labelledby=\"moreInforModalLabel\" aria-hidden=\"true\">");
//		out.append("      <div class=\"modal-dialog modal-lg\">");
//		out.append("        <div class=\"modal-content\">");
//		out.append("          <div class=\"modal-header text-bg-primary\">");
//		out.append("            <h5 class=\"modal-title fw-bold\" id=\"moreInforModalLabel\">Thông tin chi tiết hướng dẫn viên du lịch</h5>");
//		out.append("            <button type=\"button\" class=\"btn-close fs-2\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>");
//		out.append("          </div>");
//		out.append("          <div class=\"modal-body\">");
//		out.append("            <div class=\"row\">");
//		out.append("                <div class=\"col-md-6 mb-2\">");
//		out.append("                  <label for=\"lastName\" class=\"form-label\">Họ</label>");
//		out.append("                  <input type=\"text\" class=\"form-control\" id=\"lastName\" name=\"lastName\" value=\"\" disabled>");
//		out.append("                </div>");
//		out.append("                <div class=\"col-md-6 mb-2\">");
//		out.append("                  <label for=\"firstName\" class=\"form-label\">Tên</label>");
//		out.append("                  <input type=\"text\" class=\"form-control\" id=\"firstName\" name=\"firstName\" value=\"\" disabled>");
//		out.append("                </div>");
//		out.append("              </div>");
//		out.append("");
//		out.append("              <div class=\"row\">");
//		out.append("                <div class=\"col-md-6 mb-2\">");
//		out.append("                  <label for=\"dob\" class=\"form-label\">Ngày sinh</label>");
//		out.append("                  <input type=\"date\" class=\"form-control\" id=\"dob\" name=\"dob\" value=\"\" disabled>");
//		out.append("                </div>");
//		out.append("                <div class=\"col-md-6 mb-2\">");
//		out.append("                  <label for=\"gender\" class=\"form-label\">Giới tính</label>");
//		out.append("                  <select class=\"form-select\" id=\"gender\" name=\"gender\" value=\"\" disabled>");
//		out.append("                    <option value=\"Male\">Nam</option>");
//		out.append("                    <option value=\"Female\">Nữ</option>");
//		out.append("                  </select>");
//		out.append("                </div>");
//		out.append("              </div>");
//		out.append("");
//		out.append("              <div class=\"row\">");
//		out.append("                <div class=\"col-md-6 mb-2\">");
//		out.append("                  <label for=\"phoneNumber\" class=\"form-label\">Số điện thoại</label>");
//		out.append("                  <input type=\"text\" class=\"form-control\" id=\"phoneNumber\" name=\"phoneNumber\" value=\"\" disabled>");
//		out.append("                </div>");
//		out.append("                <div class=\"col-md-6 mb-2\">");
//		out.append("                  <label for=\"citizenId\" class=\"form-label\">CCCD</label>");
//		out.append("                  <input type=\"text\" class=\"form-control\" id=\"citizenId\" name=\"citizenId\" value=\"\" disabled>");
//		out.append("                </div>");
//		out.append("              </div>");
//		out.append("");
//		out.append("              <div class=\"row\">");
//		out.append("                <div class=\"col-md-6 mb-2\">");
//		out.append("                  <label for=\"cardId\" class=\"form-label\">Mã thẻ hướng dẫn</label>");
//		out.append("                  <input type=\"text\" class=\"form-control\" id=\"cardId\" name=\"cardId\" value=\"\" disabled>");
//		out.append("                </div>");
//		out.append("                <div class=\"col-md-6 mb-2\">");
//		out.append("                  <label for=\"language\" class=\"form-label\">Ngôn ngữ</label>");
//		out.append("                  <input type=\"text\" class=\"form-control\" id=\"language\" name=\"language\" value=\"\" disabled>");
//		out.append("                </div>");
//		out.append("              </div>");
//		out.append("");
//		out.append("              <div class=\"row\">");
//		out.append("                <div class=\"col-md-6 mb-2\">");
//		out.append("                  <label for=\"hometown\" class=\"form-label\">Quê quán</label>");
//		out.append("                  <input type=\"text\" class=\"form-control\" id=\"hometown\" name=\"hometown\" value=\"\" disabled>");
//		out.append("                </div>");
//		out.append("                <div class=\"col-md-6 mb-2\">");
//		out.append("                  <label for=\"address\" class=\"form-label\">Địa chỉ</label>");
//		out.append("                  <input type=\"text\" class=\"form-control\" id=\"address\" name=\"address\" value=\"\" disabled>");
//		out.append("                </div>");
//		out.append("              </div>");
//		out.append("");
//		out.append("              <div class=\"row mb-2\">");
//		out.append("                <div class=\"col-md-4 mb-2\">");
//		out.append("                  <label for=\"startDate\" class=\"form-label\">Ngày bắt đầu hợp đồng</label>");
//		out.append("                  <input type=\"date\" class=\"form-control\" id=\"startDate\" name=\"startDate\" value=\"\" disabled>");
//		out.append("                </div>");
//		out.append("                <div class=\"col-md-4 mb-2\">");
//		out.append("                  <label for=\"endDate\" class=\"form-label\">Ngày kết thúc hợp đồng</label>");
//		out.append("                  <input type=\"date\" class=\"form-control\" id=\"endDate\" name=\"endDate\" value=\"\" disabled>");
//		out.append("                </div>");
//		out.append("                <div class=\"col-md-4 mb-2\">");
//		out.append("                  <label for=\"salary\" class=\"form-label\">Lương</label>");
//		out.append("                  <input type=\"text\" class=\"form-control\" id=\"salary\" name=\"salary\" value=\"\" disabled>");
//		out.append("                </div>");
//		out.append("              </div>");
//		out.append("");
//		out.append("            <div class=\"w-100 d-flex justify-content-center\">");
//		out.append("              <button type=\"button\" class=\"btn btn-primary w-50 me-1\" data-bs-toggle=\"modal\" data-bs-target=\"#changeInforModal\"><i class=\"bx bxs-pencil me-2\"></i>Sửa</button>");
//		out.append("              <button type=\"button\" class=\"btn btn-danger w-50 ms-1\" data-bs-toggle=\"modal\" data-bs-target=\"#confirmDeleteModal\"><i class=\"bx bx-trash me-2\"></i>Xóa</button>");
//		out.append("            </div>");
//		out.append("          </div>");
//		out.append("        </div>");
//		out.append("      </div>");
//		out.append("    </div>");
		out.append("");
//		out.append("    <!-- Modal Sửa Thông Tin -->");
//		out.append("    <div class=\"modal fade\" id=\"changeInforModal\" tabindex=\"-1\" aria-labelledby=\"changeInforModalLabel\"");
//		out.append("      aria-hidden=\"true\">");
//		out.append("      <div class=\"modal-dialog modal-lg\">");
//		out.append("        <div class=\"modal-content\">");
//		out.append("          <div class=\"modal-header text-bg-primary\">");
//		out.append("            <h5 class=\"modal-title fw-bold\" id=\"changeInforModalLabel\">Sửa thông tin hướng dẫn viên du lịch</h5>");
//		out.append("            <button type=\"button\" class=\"btn-close fs-2\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>");
//		out.append("          </div>");
//		out.append("          <div class=\"modal-body\">");
//		out.append("            <form id=\"formChangeInfor\">");
//		out.append("              <div class=\"row\">");
//		out.append("                <div class=\"col-md-6 mb-2\">");
//		out.append("                  <label for=\"lastName\" class=\"form-label\">Họ</label>");
//		out.append("                  <input type=\"text\" class=\"form-control\" id=\"lastName\" name=\"lastName\" value=\"\" required>");
//		out.append("                </div>");
//		out.append("                <div class=\"col-md-6 mb-2\">");
//		out.append("                  <label for=\"firstName\" class=\"form-label\">Tên</label>");
//		out.append("                  <input type=\"text\" class=\"form-control\" id=\"firstName\" name=\"firstName\" value=\"\" required>");
//		out.append("                </div>");
//		out.append("              </div>");
//		out.append("");
//		out.append("              <div class=\"row\">");
//		out.append("                <div class=\"col-md-6 mb-2\">");
//		out.append("                  <label for=\"dob\" class=\"form-label\">Ngày sinh</label>");
//		out.append("                  <input type=\"date\" class=\"form-control\" id=\"dob\" name=\"dob\" value=\"\" required>");
//		out.append("                </div>");
//		out.append("                <div class=\"col-md-6 mb-2\">");
//		out.append("                  <label for=\"gender\" class=\"form-label\">Giới tính</label>");
//		out.append("                  <select class=\"form-select\" id=\"gender\" name=\"gender\" value=\"\" required>");
//		out.append("                    <option value=\"Male\">Nam</option>");
//		out.append("                    <option value=\"Female\">Nữ</option>");
//		out.append("                  </select>");
//		out.append("                </div>");
//		out.append("              </div>");
//		out.append("");
//		out.append("              <div class=\"row\">");
//		out.append("                <div class=\"col-md-6 mb-2\">");
//		out.append("                  <label for=\"phoneNumber\" class=\"form-label\">Số điện thoại</label>");
//		out.append("                  <input type=\"text\" minlength=\"10\" maxlength=\"10\" class=\"form-control\" id=\"phoneNumber\" name=\"phoneNumber\" value=\"\" required>");
//		out.append("                </div>");
//		out.append("                <div class=\"col-md-6 mb-2\">");
//		out.append("                  <label for=\"citizenId\" class=\"form-label\">CCCD</label>");
//		out.append("                  <input type=\"text\" minlength=\"12\" maxlength=\"12\" class=\"form-control\" id=\"citizenId\" name=\"citizenId\" value=\"\" required>");
//		out.append("                </div>");
//		out.append("              </div>");
//		out.append("");
//		out.append("              <div class=\"row\">");
//		out.append("                <div class=\"col-md-6 mb-2\">");
//		out.append("                  <label for=\"cardId\" class=\"form-label\">Mã thẻ hướng dẫn</label>");
//		out.append("                  <input type=\"text\" minlength=\"12\" maxlength=\"12\" class=\"form-control\" id=\"cardId\" name=\"cardId\" value=\"\" required>");
//		out.append("                </div>");
//		out.append("                <div class=\"col-md-6 mb-2\">");
//		out.append("                  <label for=\"language\" class=\"form-label\">Ngôn ngữ</label>");
//		out.append("                  <input type=\"text\" class=\"form-control\" id=\"language\" name=\"language\" value=\"\" required>");
//		out.append("                </div>");
//		out.append("              </div>");
//		out.append("");
//		out.append("              <div class=\"row\">");
//		out.append("                <div class=\"col-md-6 mb-2\">");
//		out.append("                  <label for=\"hometown\" class=\"form-label\">Quê quán</label>");
//		out.append("                  <input type=\"text\" class=\"form-control\" id=\"hometown\" name=\"hometown\" value=\"\" required>");
//		out.append("                </div>");
//		out.append("                <div class=\"col-md-6 mb-2\">");
//		out.append("                  <label for=\"address\" class=\"form-label\">Địa chỉ</label>");
//		out.append("                  <input type=\"text\" class=\"form-control\" id=\"address\" name=\"address\" value=\"\" required>");
//		out.append("                </div>");
//		out.append("              </div>");
//		out.append("");
//		out.append("              <div class=\"row mb-2\">");
//		out.append("                <div class=\"col-md-4 mb-2\">");
//		out.append("                  <label for=\"startDate\" class=\"form-label\">Ngày bắt đầu hợp đồng</label>");
//		out.append("                  <input type=\"date\" class=\"form-control\" id=\"startDate\" name=\"startDate\" value=\"\" required>");
//		out.append("                </div>");
//		out.append("                <div class=\"col-md-4 mb-2\">");
//		out.append("                  <label for=\"endDate\" class=\"form-label\">Ngày kết thúc hợp đồng</label>");
//		out.append("                  <input type=\"date\" class=\"form-control\" id=\"endDate\" name=\"endDate\" value=\"\" required>");
//		out.append("                </div>");
//		out.append("                <div class=\"col-md-4 mb-2\">");
//		out.append("                  <label for=\"salary\" class=\"form-label\">Lương</label>");
//		out.append("                  <input type=\"text\" class=\"form-control\" id=\"salary\" name=\"salary\" value=\"\" required>");
//		out.append("                </div>");
//		out.append("              </div>");
//		out.append("");
//		out.append("              <button type=\"submit\" class=\"btn btn-primary w-100\">Lưu thay đổi</button>");
//		out.append("            </form>");
//		out.append("          </div>");
//		out.append("        </div>");
//		out.append("      </div>");
//		out.append("    </div>");
		out.append("");
//		out.append("    <!-- Modal Xác Nhận Xóa -->");
//		out.append("    <div class=\"modal fade\" id=\"confirmDeleteModal\" tabindex=\"-1\" aria-labelledby=\"confirmDeleteModalLabel\"");
//		out.append("      aria-hidden=\"true\">");
//		out.append("      <div class=\"modal-dialog\">");
//		out.append("        <div class=\"modal-content\">");
//		out.append("          <div class=\"modal-header text-bg-danger\">");
//		out.append("            <h5 class=\"modal-title text-light fw-bold\" id=\"confirmDeleteModalLabel\">Xác nhận xóa</h5>");
//		out.append("            <button type=\"button\" class=\"btn-close fs-2\" data-bs-dismiss=\"modal\" aria-label=\"Đóng\"></button>");
//		out.append("          </div>");
//		out.append("          <div class=\"modal-body\">");
//		out.append("            Bạn có chắc chắn muốn xóa không?");
//		out.append("          </div>");
//		out.append("          <div class=\"modal-footer\">");
//		out.append("            <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">Hủy</button>");
//		out.append("            <button type=\"submit\" class=\"btn btn-danger\">Xóa</button>");
//		out.append("          </div>");
//		out.append("        </div>");
//		out.append("      </div>");
//		out.append("    </div>");
		out.append("    <!-- End Modal -->");
		out.append("  </main><!-- End #main -->");
		out.append("");
		out.append("  <!-- ======= Footer ======= -->");
		out.append("  <footer id=\"footer\" class=\"footer\">");
		out.append("    <div class=\"copyright\">");
		out.append("      &copy; Copyright <strong><span>TravelVN</span></strong>. All Rights Reserved");
		out.append("    </div>");
		out.append("  </footer><!-- End Footer -->");
		out.append("");
		out.append("  <a href=\"#\" class=\"back-to-top d-flex align-items-center justify-content-center\"><i");
		out.append("      class=\"bi bi-arrow-up-short\"></i></a>");
		out.append("");
		out.append("  <!-- JS Customize -->");
		out.append("  <script src=\"assets/js/dataTableCustom.js\"></script>");
		out.append("");
		out.append("  <!-- Vendor JS Files -->");
		out.append("  <script src=\"assets/vendor/apexcharts/apexcharts.min.js\"></script>");
		out.append("  <script src=\"assets/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>");
		out.append("  <script src=\"assets/vendor/chart.js/chart.umd.js\"></script>");
		out.append("  <script src=\"assets/vendor/echarts/echarts.min.js\"></script>");
		out.append("  <script src=\"assets/vendor/quill/quill.js\"></script>");
		out.append("  <script src=\"assets/vendor/simple-datatables/simple-datatables.js\"></script>");
		out.append("  <script src=\"assets/vendor/tinymce/tinymce.min.js\"></script>");
		out.append("  <script src=\"assets/vendor/php-email-form/validate.js\"></script>");
		out.append("");
		out.append("  <!-- Template Main JS File -->");
		out.append("  <script src=\"assets/js/main.js\"></script>");
		out.append("");
		out.append("</body>");
		out.append("");
		out.append("</html>");
	}
}
