package ads.to;

import java.io.IOException;
import java.io.PrintWriter;

import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

@WebServlet("/User-Profile")
public class UserProfileServlet extends HttpServlet{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Override
	protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
		// TODO Auto-generated method stub
		resp.setCharacterEncoding("UTF-8");
		 resp.setContentType("text/html; charset=UTF-8");
		PrintWriter out = resp.getWriter();
		out.append("<!DOCTYPE html>");
		out.append("<html lang=\"en\">");
		out.append("");
		out.append("<head>");
		  out.append("<meta charset=\"utf-8\">");
		  out.append("<meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">");
		out.append("");
		  out.append("<title>Hồ sơ người dùng</title>");
		  out.append("<meta content=\"\" name=\"description\">");
		  out.append("<meta content=\"\" name=\"keywords\">");
		out.append("");
		  out.append("<!-- Favicons -->");
		  out.append("<link href=\"assets/img/favicon.png\" rel=\"icon\">");
		  out.append("<link href=\"assets/img/apple-touch-icon.png\" rel=\"apple-touch-icon\">");
		out.append("");
		  out.append("<!-- Google Fonts -->");
		  out.append("<link href=\"https://fonts.gstatic.com\" rel=\"preconnect\">");
		  out.append("<link href=\"https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i\" rel=\"stylesheet\">");
		out.append("");
		  out.append("<!-- Vendor CSS Files -->");
		  out.append("<link href=\"assets/vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">");
		  out.append("<link href=\"assets/vendor/bootstrap-icons/bootstrap-icons.css\" rel=\"stylesheet\">");
		  out.append("<link href=\"assets/vendor/boxicons/css/boxicons.min.css\" rel=\"stylesheet\">");
		  out.append("<link href=\"assets/vendor/quill/quill.snow.css\" rel=\"stylesheet\">");
		  out.append("<link href=\"assets/vendor/quill/quill.bubble.css\" rel=\"stylesheet\">");
		  out.append("<link href=\"assets/vendor/remixicon/remixicon.css\" rel=\"stylesheet\">");
		  out.append("<link href=\"assets/vendor/simple-datatables/style.css\" rel=\"stylesheet\">");
		out.append("");
		  out.append("<!-- Template Main CSS File -->");
		  out.append("<link href=\"assets/css/style.css\" rel=\"stylesheet\">");
		out.append("");
		  out.append("<!-- =======================================================");
		  out.append("* Template Name: NiceAdmin");
		  out.append("* Template URL: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/");
		  out.append("* Updated: Apr 20 2024 with Bootstrap v5.3.3");
		  out.append("* Author: BootstrapMade.com");
		  out.append("* License: https://bootstrapmade.com/license/");
		  out.append("======================================================== -->");
		out.append("</head>");
		out.append("");
		out.append("<body>");
		out.append("");
		  out.append("<!-- ======= Header ======= -->");
		  out.append("<header id=\"header\" class=\"header fixed-top d-flex align-items-center\">");
		out.append("");
		    out.append("<div class=\"d-flex align-items-center justify-content-between\">");
		      out.append("<a href=\"index.html\" class=\"logo d-flex align-items-center\" style=\"height: max-content;\">");
		        out.append("<img src=\"resources/Asset 2.svg\" alt=\"\" style=\"height: 100px; width: 40px;\" >");
		        out.append("<span class=\"d-none d-lg-block\">TravelVN</span>");
		      out.append("</a>");
		    out.append("</div><!-- End Logo -->");
		    out.append("<i class=\"bi bi-list toggle-sidebar-btn\"></i>");
		out.append("");
		    out.append("<div class=\"search-bar\">");
		      out.append("<script>");
		         out.append("async function getData() {");
		          out.append("query = document.getElementById(\"name\").value;");
		                      out.append("const url = \"http://localhost:8083/user/List-with-multiple-searching-columns?pageNo=0&pageSize=10&search=firstName:\"+query;;");
		                      out.append("try {");
		                        out.append("const response = await fetch(url);");
		                        out.append("if (!response.ok) {");
		                          out.append("throw new Error(`Response status: ${response.status}`);");
		                        out.append("}");
		out.append("");
		                        out.append("const json = await response.json();");
		                        out.append("console.log(json);");
		                      out.append("} catch (error) {");
		                        out.append("console.error(error.message);");
		                      out.append("}");
		                    out.append("}");
		      out.append("</script>");
		      out.append("<form class=\"search-form d-flex align-items-center\" method=\"GET\" action=\"#\">");
		        out.append("<input type=\"text\" name=\"query\" placeholder=\"Tìm kiếm\" title=\"Enter search keyword\" id=\"name\">");
		        out.append("<button type=\"submit\" title=\"Search\"><i class=\"bi bi-search\" onclick=getData()></i></button>");
		      out.append("</form>");
		    out.append("</div><!-- End Search Bar -->");
		out.append("");
		    out.append("<nav class=\"header-nav ms-auto\">");
		      out.append("<ul class=\"d-flex align-items-center\">");
		out.append("");
		        out.append("<li class=\"nav-item d-block d-lg-none\">");
		          out.append("<a class=\"nav-link nav-icon search-bar-toggle \" href=\"#\">");
		            out.append("<i class=\"bi bi-search\"></i>");
		          out.append("</a>");
		        out.append("</li><!-- End Search Icon-->");
		out.append("");
		        out.append("<li class=\"nav-item dropdown\">");
		out.append("");
		          out.append("<a class=\"nav-link nav-icon\" href=\"#\" data-bs-toggle=\"dropdown\">");
		            out.append("<i class=\"bi bi-bell\"></i>");
		            out.append("<span class=\"badge bg-primary badge-number\">4</span>");
		          out.append("</a><!-- End Notification Icon -->");
		out.append("");
		          out.append("<ul class=\"dropdown-menu dropdown-menu-end dropdown-menu-arrow notifications\">");
		            out.append("<li class=\"dropdown-header\">");
		              out.append("You have 4 new notifications");
		              out.append("<a href=\"#\"><span class=\"badge rounded-pill bg-primary p-2 ms-2\">View all</span></a>");
		            out.append("</li>");
		            out.append("<li>");
		              out.append("<hr class=\"dropdown-divider\">");
		            out.append("</li>");
		out.append("");
		            out.append("<li class=\"notification-item\">");
		              out.append("<i class=\"bi bi-exclamation-circle text-warning\"></i>");
		              out.append("<div>");
		                out.append("<h4>Lorem Ipsum</h4>");
		                out.append("<p>Quae dolorem earum veritatis oditseno</p>");
		                out.append("<p>30 min. ago</p>");
		              out.append("</div>");
		            out.append("</li>");
		out.append("");
		            out.append("<li>");
		              out.append("<hr class=\"dropdown-divider\">");
		            out.append("</li>");
		out.append("");
		            out.append("<li class=\"notification-item\">");
		              out.append("<i class=\"bi bi-x-circle text-danger\"></i>");
		              out.append("<div>");
		                out.append("<h4>Atque rerum nesciunt</h4>");
		                out.append("<p>Quae dolorem earum veritatis oditseno</p>");
		                out.append("<p>1 hr. ago</p>");
		              out.append("</div>");
		            out.append("</li>");
		out.append("");
		            out.append("<li>");
		              out.append("<hr class=\"dropdown-divider\">");
		            out.append("</li>");
		out.append("");
		            out.append("<li class=\"notification-item\">");
		              out.append("<i class=\"bi bi-check-circle text-success\"></i>");
		              out.append("<div>");
		                out.append("<h4>Sit rerum fuga</h4>");
		                out.append("<p>Quae dolorem earum veritatis oditseno</p>");
		                out.append("<p>2 hrs. ago</p>");
		              out.append("</div>");
		            out.append("</li>");
		out.append("");
		            out.append("<li>");
		              out.append("<hr class=\"dropdown-divider\">");
		            out.append("</li>");
		out.append("");
		            out.append("<li class=\"notification-item\">");
		              out.append("<i class=\"bi bi-info-circle text-primary\"></i>");
		              out.append("<div>");
		                out.append("<h4>Dicta reprehenderit</h4>");
		                out.append("<p>Quae dolorem earum veritatis oditseno</p>");
		                out.append("<p>4 hrs. ago</p>");
		              out.append("</div>");
		            out.append("</li>");
		out.append("");
		            out.append("<li>");
		              out.append("<hr class=\"dropdown-divider\">");
		            out.append("</li>");
		            out.append("<li class=\"dropdown-footer\">");
		              out.append("<a href=\"#\">Show all notifications</a>");
		            out.append("</li>");
		out.append("");
		          out.append("</ul><!-- End Notification Dropdown Items -->");
		out.append("");
		        out.append("</li><!-- End Notification Nav -->");
		out.append("");
		        out.append("<li class=\"nav-item dropdown\">");
		out.append("");
		          out.append("<a class=\"nav-link nav-icon\" href=\"#\" data-bs-toggle=\"dropdown\">");
		            out.append("<i class=\"bi bi-chat-left-text\"></i>");
		            out.append("<span class=\"badge bg-success badge-number\">3</span>");
		          out.append("</a><!-- End Messages Icon -->");
		out.append("");
		          out.append("<ul class=\"dropdown-menu dropdown-menu-end dropdown-menu-arrow messages\">");
		            out.append("<li class=\"dropdown-header\">");
		              out.append("You have 3 new messages");
		              out.append("<a href=\"#\"><span class=\"badge rounded-pill bg-primary p-2 ms-2\">View all</span></a>");
		            out.append("</li>");
		            out.append("<li>");
		              out.append("<hr class=\"dropdown-divider\">");
		            out.append("</li>");
		out.append("");
		            out.append("<li class=\"message-item\">");
		              out.append("<a href=\"#\">");
		                out.append("<img src=\"assets/img/messages-1.jpg\" alt=\"\" class=\"rounded-circle\">");
		                out.append("<div>");
		                  out.append("<h4>Maria Hudson</h4>");
		                  out.append("<p>Velit asperiores et ducimus soluta repudiandae labore officia est ut...</p>");
		                  out.append("<p>4 hrs. ago</p>");
		                out.append("</div>");
		              out.append("</a>");
		            out.append("</li>");
		            out.append("<li>");
		              out.append("<hr class=\"dropdown-divider\">");
		            out.append("</li>");
		out.append("");
		            out.append("<li class=\"message-item\">");
		              out.append("<a href=\"#\">");
		                out.append("<img src=\"assets/img/messages-2.jpg\" alt=\"\" class=\"rounded-circle\">");
		                out.append("<div>");
		                  out.append("<h4>Anna Nelson</h4>");
		                  out.append("<p>Velit asperiores et ducimus soluta repudiandae labore officia est ut...</p>");
		                  out.append("<p>6 hrs. ago</p>");
		                out.append("</div>");
		              out.append("</a>");
		            out.append("</li>");
		            out.append("<li>");
		              out.append("<hr class=\"dropdown-divider\">");
		            out.append("</li>");
		out.append("");
		            out.append("<li class=\"message-item\">");
		              out.append("<a href=\"#\">");
		                out.append("<img src=\"assets/img/messages-3.jpg\" alt=\"\" class=\"rounded-circle\">");
		                out.append("<div>");
		                  out.append("<h4>David Muldon</h4>");
		                  out.append("<p>Velit asperiores et ducimus soluta repudiandae labore officia est ut...</p>");
		                  out.append("<p>8 hrs. ago</p>");
		                out.append("</div>");
		              out.append("</a>");
		            out.append("</li>");
		            out.append("<li>");
		              out.append("<hr class=\"dropdown-divider\">");
		            out.append("</li>");
		out.append("");
		            out.append("<li class=\"dropdown-footer\">");
		              out.append("<a href=\"#\">Show all messages</a>");
		            out.append("</li>");
		out.append("");
		          out.append("</ul><!-- End Messages Dropdown Items -->");
		out.append("");
		        out.append("</li><!-- End Messages Nav -->");
		out.append("");
		        out.append("<li class=\"nav-item dropdown pe-3\">");
		out.append("");
		          out.append("<a class=\"nav-link nav-profile d-flex align-items-center pe-0\" href=\"#\" data-bs-toggle=\"dropdown\">");
		            out.append("<img src=\"assets/img/profile-img.jpg\" alt=\"Profile\" class=\"rounded-circle\">");
		            out.append("<span class=\"d-none d-md-block dropdown-toggle ps-2\">Kiều Đức Thịnh</span>");
		          out.append("</a><!-- End Profile Iamge Icon -->");
		out.append("");
		          out.append("<ul class=\"dropdown-menu dropdown-menu-end dropdown-menu-arrow profile\">");
		            out.append("<li class=\"dropdown-header\">");
		              out.append("<h6>Kiều Đức Thịnh</h6>");
		              out.append("<span>Business analyst</span>");
		            out.append("</li>");
		            out.append("<li>");
		              out.append("<hr class=\"dropdown-divider\">");
		            out.append("</li>");
		out.append("");
		            out.append("<li>");
		              out.append("<a class=\"dropdown-item d-flex align-items-center\" href=\"users-profile.html\">");
		                out.append("<i class=\"bi bi-person\"></i>");
		                out.append("<span>Hồ sơ cá nhân</span>");
		              out.append("</a>");
		            out.append("</li>");
		            out.append("<li>");
		              out.append("<hr class=\"dropdown-divider\">");
		            out.append("</li>");
		out.append("");
		            out.append("<li>");
		              out.append("<a class=\"dropdown-item d-flex align-items-center\" href=\"users-profile.html\">");
		                out.append("<i class=\"bi bi-gear\"></i>");
		                out.append("<span>Cài đặt tài khoản</span>");
		              out.append("</a>");
		            out.append("</li>");
		            out.append("<li>");
		              out.append("<hr class=\"dropdown-divider\">");
		            out.append("</li>");
		out.append("");
		            out.append("<li>");
		              out.append("<a class=\"dropdown-item d-flex align-items-center\" href=\"pages-faq.html\">");
		                out.append("<i class=\"bi bi-question-circle\"></i>");
		                out.append("<span>Trợ giúp</span>");
		              out.append("</a>");
		            out.append("</li>");
		            out.append("<li>");
		              out.append("<hr class=\"dropdown-divider\">");
		            out.append("</li>");
		out.append("");
		            out.append("<li>");
		              out.append("<a class=\"dropdown-item d-flex align-items-center\" href=\"#\">");
		                out.append("<i class=\"bi bi-box-arrow-right\"></i>");
		                out.append("<span>Đăng xuất</span>");
		              out.append("</a>");
		            out.append("</li>");
		out.append("");
		          out.append("</ul><!-- End Profile Dropdown Items -->");
		        out.append("</li><!-- End Profile Nav -->");
		out.append("");
		      out.append("</ul>");
		    out.append("</nav><!-- End Icons Navigation -->");
		out.append("");
		  out.append("</header><!-- End Header -->");
		out.append("");
		   out.append("<!-- ======= Sidebar ======= -->");
		   out.append("<aside id=\"sidebar \" class=\"sidebar\">");
		out.append("");
		    out.append("<ul class=\"sidebar-nav\" id=\"sidebar-nav\">");
		out.append("");
		      out.append("<li class=\"nav-item\">");
		        out.append("<a class=\"nav-link \" href=\"index.html\">");
		          out.append("<i class=\"bi bi-grid\"></i>");
		          out.append("<span>Dashboard</span>");
		        out.append("</a>");
		      out.append("</li><!-- End Dashboard Nav -->");
		out.append("");
		      out.append("<li class=\"nav-item\">");
		        out.append("<a class=\"nav-link collapsed\"  href=\"Tour_management.html\">");
		          out.append("<i class=\"bi bi-layout-text-window-reverse\"></i><span>Quản lý tour</span>");
		        out.append("<ul id=\"tables-nav\" class=\"nav-content collapse \" data-bs-parent=\"#sidebar-nav\">");
		          out.append("<li>");
		            out.append("<a href=\"tables-general.html\">");
		              out.append("<i class=\"bi bi-circle\"></i><span>Table general</span>");
		            out.append("</a>");
		          out.append("</li>");
		          out.append("<li>");
		            out.append("<a href=\"Tour_unit_management.html\">");
		              out.append("<i class=\"bi bi-circle\"></i><span>Danh sách tour</span>");
		            out.append("</a>");
		          out.append("</li>");
		        out.append("</ul>");
		      out.append("</li><!-- End Tables Nav -->");
		out.append("");
		      out.append("<li class=\"nav-item\">");
		        out.append("<a class=\"nav-link collapsed\" data-bs-target=\"#charts-nav\" href=\"Festival_management.html\">");
		          out.append("<i class=\"bi bi-flower1\"></i>");
		out.append("");
		    out.append("<span>Quản lý lễ hội</span>");
		        out.append("</a>");
		      out.append("</li><!-- End Charts Nav -->");
		      out.append("<li class=\"nav-item\">");
		        out.append("<a class=\"nav-link collapsed\" data-bs-target=\"#charts-nav\" href=\"Discount-management.html\">");
		          out.append("<i class=\"bi bi-coin\"></i>");
		out.append("");
		    out.append("<span>Chương trình giảm giá</span>");
		        out.append("</a>");
		      out.append("</li><!-- End Charts Nav -->");
		      out.append("<li class=\"nav-item\">");
		        out.append("<a class=\"nav-link collapsed\" data-bs-target=\"#charts-nav\" href=\"tour_guide_management.html\">");
		          out.append("<i class=\"bi bi-flag-fill\"></i>");
		out.append("");
		    out.append("<span>Hướng dẫn viên</span>");
		        out.append("</a>");
		      out.append("</li><!-- End Charts Nav -->");
		out.append("");
		out.append("      ");
		      out.append("<li class=\"nav-item\">");
		        out.append("<a class=\"nav-link collapsed\" data-bs-target=\"#charts-nav\" href=\"approve_request_cancel_booking.html\">");
		          out.append("<i class=\"bi bi-card-checklist\"></i>");
		          out.append("<span>Yêu cầu huỷ tour</span>");
		        out.append("</a>");
		      out.append("</li>");
		      out.append("<li class=\"nav-item\">");
		        out.append("<a class=\"nav-link collapsed\" data-bs-target=\"#charts-nav\" href=\"Customer_info_management.html\">");
		          out.append("<i class=\"bi bi-people-fill\"></i>");
		          out.append("<span>Khách hàng</span>");
		        out.append("</a>");
		      out.append("</li><!-- End Charts Nav -->");
		out.append("");
		out.append("");
		      out.append("<li class=\"nav-item\">");
		        out.append("<a class=\"nav-link collapsed\" href=\"users-profile.html\">");
		          out.append("<i class=\"bi bi-person\"></i>");
		          out.append("<span>Thông tin cá nhân</span>");
		        out.append("</a>");
		      out.append("</li><!-- End Profile Page Nav -->");
		out.append("");
		      out.append("<li class=\"nav-heading\">Khác</li>");
		out.append("");
		out.append("");
		      out.append("<li class=\"nav-item\">");
		        out.append("<a class=\"nav-link collapsed\" href=\"pages-faq.html\">");
		          out.append("<i class=\"bi bi-question-circle\"></i>");
		          out.append("<span>Hướng dẫn sử dụng</span>");
		        out.append("</a>");
		      out.append("</li><!-- End F.A.Q Page Nav -->");
		out.append("");
		      out.append("<li class=\"nav-item\">");
		        out.append("<a class=\"nav-link collapsed\" href=\"pages-contact.html\">");
		          out.append("<i class=\"bi bi-envelope\"></i>");
		          out.append("<span>Liên hệ với admin</span>");
		        out.append("</a>");
		      out.append("</li><!-- End Contact Page Nav -->");
		      out.append("<li class=\"nav-item\">");
		        out.append("<a class=\"nav-link collapsed\" href=\"pages-contact.html\">");
		          out.append("<i class=\"bi bi-gear\"></i>");
		          out.append("<span>Cài đặt</span>");
		        out.append("</a>");
		      out.append("</li><!-- End Contact Page Nav -->");
		out.append("");
		out.append("");
		    out.append("</ul>");
		out.append("");
		  out.append("</aside><!-- End Sidebar-->");
		out.append("");
		  out.append("<main id=\"main\" class=\"main\">");
		out.append("");
		    out.append("<div class=\"pagetitle\">");
		      out.append("<h1>Thông tin cá nhân</h1>");
		      out.append("<nav>");
		        out.append("<ol class=\"breadcrumb\">");
		          out.append("<li class=\"breadcrumb-item\"><a href=\"index.html\">Home</a></li>");
		          out.append("<li class=\"breadcrumb-item\">Người dùng</li>");
		          out.append("<li class=\"breadcrumb-item active\">Thông tin cá nhân</li>");
		        out.append("</ol>");
		      out.append("</nav>");
		    out.append("</div><!-- End Page Title -->");
		out.append("");
		    out.append("<section class=\"section profile\">");
		      out.append("<div class=\"row\">");
		        out.append("<div class=\"col-xl-4\">");
		out.append("");
		          out.append("<div class=\"card\">");
		            out.append("<div class=\"card-body profile-card pt-4 d-flex flex-column align-items-center\">");
		out.append("");
		out.append("");
		              out.append("<img src=\"assets/img/profile-img.jpg\" alt=\"Profile\" class=\"rounded-circle\">");
		              out.append("<h2>Kevin Anderson</h2>");
		              out.append("<h3>Web Designer</h3>");
		              out.append("<div class=\"social-links mt-2\">");
		                out.append("<a href=\"#\" class=\"twitter\"><i class=\"bi bi-twitter\"></i></a>");
		                out.append("<a href=\"#\" class=\"facebook\"><i class=\"bi bi-facebook\"></i></a>");
		                out.append("<a href=\"#\" class=\"instagram\"><i class=\"bi bi-instagram\"></i></a>");
		                out.append("<a href=\"#\" class=\"linkedin\"><i class=\"bi bi-linkedin\"></i></a>");
		              out.append("</div>");
		            out.append("</div>");
		          out.append("</div>");
		out.append("");
		        out.append("</div>");
		out.append("");
		        out.append("<div class=\"col-xl-8\">");
		out.append("");
		          out.append("<div class=\"card\">");
		            out.append("<div class=\"card-body pt-3\">");
		              out.append("<!-- Bordered Tabs -->");
		              out.append("<ul class=\"nav nav-tabs nav-tabs-bordered\">");
		out.append("");
		                out.append("<li class=\"nav-item\">");
		                  out.append("<button class=\"nav-link active\" data-bs-toggle=\"tab\" data-bs-target=\"#profile-overview\">Tổng quan</button>");
		                out.append("</li>");
		out.append("");
		                out.append("<li class=\"nav-item\">");
		                  out.append("<button class=\"nav-link\" data-bs-toggle=\"tab\" data-bs-target=\"#profile-edit\">Sửa thông tin cá nhân</button>");
		                out.append("</li>");
		out.append("");
		                out.append("<li class=\"nav-item\">");
		                  out.append("<button class=\"nav-link\" data-bs-toggle=\"tab\" data-bs-target=\"#profile-settings\">Cài đặt</button>");
		                out.append("</li>");
		out.append("");
		                out.append("<li class=\"nav-item\">");
		                  out.append("<button class=\"nav-link\" data-bs-toggle=\"tab\" data-bs-target=\"#profile-change-password\">Đổi mật khẩu</button>");
		                out.append("</li>");
		out.append("");
		              out.append("</ul>");
		              out.append("<div class=\"tab-content pt-2\">");
		out.append("");
		                out.append("<div class=\"tab-pane fade show active profile-overview\" id=\"profile-overview\">");
		                  out.append("<h5 class=\"card-title\">Giới thiệu chung</h5>");
		                  out.append("<p class=\"small\">");
		                    out.append("Sunt est soluta temporibus accusantium neque nam maiores cumque temporibus. Tempora libero non est unde veniam est qui dolor. Ut sunt iure rerum quae quisquam autem eveniet perspiciatis odit. Fuga sequi sed ea saepe at unde.");
		                  out.append("</p>");
		out.append("");
		                  out.append("<h5 class=\"card-title\">Thông tin cá nhân</h5>");
		out.append("");
		                  out.append("<div class=\"row\">");
		                    out.append("<div class=\"col-lg-3 col-md-4 label \">Họ và tên</div>");
		                    out.append("<div class=\"col-lg-9 col-md-8\">Kiều Đức Thịnh</div>");
		                  out.append("</div>");
		out.append("");
		                  out.append("<div class=\"row\">");
		                    out.append("<div class=\"col-lg-3 col-md-4 label\">Ngày sinh</div>");
		                    out.append("<div class=\"col-lg-9 col-md-8\">03-03-2004</div>");
		                  out.append("</div>");
		out.append("");
		                  out.append("<div class=\"row\">");
		                    out.append("<div class=\"col-lg-3 col-md-4 label\">Giới tính</div>");
		                    out.append("<div class=\"col-lg-9 col-md-8\">Nam</div>");
		                  out.append("</div>");
		out.append("");
		                  out.append("<div class=\"row\">");
		                    out.append("<div class=\"col-lg-3 col-md-4 label\">Địa chỉ</div>");
		                    out.append("<div class=\"col-lg-9 col-md-8\">Hà Nội</div>");
		                  out.append("</div>");
		out.append("");
		                  out.append("<div class=\"row\">");
		                    out.append("<div class=\"col-lg-3 col-md-4 label\">Số điện thoại</div>");
		                    out.append("<div class=\"col-lg-9 col-md-8\">0123456789</div>");
		                  out.append("</div>");
		out.append("");
		                  out.append("<div class=\"row\">");
		                    out.append("<div class=\"col-lg-3 col-md-4 label\">Mã căn cước công dân</div>");
		                    out.append("<div class=\"col-lg-9 col-md-8\">001240459953</div>");
		                  out.append("</div>");
		out.append("");
		                  out.append("<div class=\"row\">");
		                    out.append("<div class=\"col-lg-3 col-md-4 label\">Email</div>");
		                    out.append("<div class=\"col-lg-9 col-md-8\">k.anderson@example.com</div>");
		                  out.append("</div>");
		out.append("");
		                out.append("</div>");
		out.append("");
		                out.append("<div class=\"tab-pane fade profile-edit pt-3\" id=\"profile-edit\">");
		out.append("");
		                  out.append("<!-- Profile Edit Form -->");
		                  out.append("<form>");
		                    out.append("<div class=\"row mb-3\">");
		                      out.append("<label for=\"profileImage\" class=\"col-md-4 col-lg-3 col-form-label\">Ảnh đại diện</label>");
		                      out.append("<div class=\"col-md-8 col-lg-9\">");
		                        out.append("<img src=\"assets/img/profile-img.jpg\" alt=\"Profile\">");
		                        out.append("<div class=\"pt-2\">");
		                          out.append("<a href=\"#\" class=\"btn btn-primary btn-sm\" title=\"Upload new profile image\"><i class=\"bi bi-upload\"></i></a>");
		                          out.append("<a href=\"#\" class=\"btn btn-danger btn-sm\" title=\"Remove my profile image\"><i class=\"bi bi-trash\"></i></a>");
		                        out.append("</div>");
		                      out.append("</div>");
		                    out.append("</div>");
		out.append("");
		                    out.append("<div class=\"row mb-3\">");
		                      out.append("<label for=\"fullName\" class=\"col-md-4 col-lg-3 col-form-label\">Họ và tên</label>");
		                      out.append("<div class=\"col-md-8 col-lg-9\">");
		                        out.append("<input name=\"fullName\" type=\"text\" class=\"form-control\" id=\"fullName\" value=\"Kevin Anderson\">");
		                      out.append("</div>");
		                    out.append("</div>");
		out.append("");
		                    out.append("<div class=\"row mb-3\">");
		                      out.append("<label for=\"about\" class=\"col-md-4 col-lg-3 col-form-label\">Về tôi</label>");
		                      out.append("<div class=\"col-md-8 col-lg-9\">");
		                        out.append("<textarea name=\"about\" class=\"form-control\" id=\"about\" style=\"height: 100px\">Sunt est soluta temporibus accusantium neque nam maiores cumque temporibus. Tempora libero non est unde veniam est qui dolor. Ut sunt iure rerum quae quisquam autem eveniet perspiciatis odit. Fuga sequi sed ea saepe at unde.</textarea>");
		                      out.append("</div>");
		                    out.append("</div>");
		out.append("");
		                    out.append("<div class=\"row mb-3\">");
		                      out.append("<label for=\"company\" class=\"col-md-4 col-lg-3 col-form-label\">Số điện thoại</label>");
		                      out.append("<div class=\"col-md-8 col-lg-9\">");
		                        out.append("<input name=\"company\" type=\"text\" class=\"form-control\" id=\"company\" value=\"Lueilwitz, Wisoky and Leuschke\">");
		                      out.append("</div>");
		                    out.append("</div>");
		out.append("");
		                    out.append("<div class=\"row mb-3\">");
		                      out.append("<label for=\"Job\" class=\"col-md-4 col-lg-3 col-form-label\">Số căn cước</label>");
		                      out.append("<div class=\"col-md-8 col-lg-9\">");
		                        out.append("<input name=\"job\" type=\"text\" class=\"form-control\" id=\"Job\" value=\"Web Designer\">");
		                      out.append("</div>");
		                    out.append("</div>");
		out.append("");
		                    out.append("<div class=\"row mb-3\">");
		                      out.append("<label for=\"Country\" class=\"col-md-4 col-lg-3 col-form-label\">Giới tính</label>");
		                      out.append("<div class=\"col-md-8 col-lg-9\">");
		                        out.append("<input name=\"country\" type=\"text\" class=\"form-control\" id=\"Country\" value=\"USA\">");
		                      out.append("</div>");
		                    out.append("</div>");
		out.append("");
		                    out.append("<div class=\"row mb-3\">");
		                      out.append("<label for=\"Address\" class=\"col-md-4 col-lg-3 col-form-label\">Địa chỉ</label>");
		                      out.append("<div class=\"col-md-8 col-lg-9\">");
		                        out.append("<input name=\"address\" type=\"text\" class=\"form-control\" id=\"Address\" value=\"A108 Adam Street, New York, NY 535022\">");
		                      out.append("</div>");
		                    out.append("</div>");
		out.append("");
		                    out.append("<div class=\"row mb-3\">");
		                      out.append("<label for=\"Phone\" class=\"col-md-4 col-lg-3 col-form-label\">Ngày sinh</label>");
		                      out.append("<div class=\"col-md-8 col-lg-9\">");
		                        out.append("<input name=\"phone\" type=\"text\" class=\"form-control\" id=\"Phone\" value=\"(436) 486-3538 x29071\">");
		                      out.append("</div>");
		                    out.append("</div>");
		out.append("");
		                    out.append("<div class=\"row mb-3\">");
		                      out.append("<label for=\"Email\" class=\"col-md-4 col-lg-3 col-form-label\">Email</label>");
		                      out.append("<div class=\"col-md-8 col-lg-9\">");
		                        out.append("<input name=\"email\" type=\"email\" class=\"form-control\" id=\"Email\" value=\"k.anderson@example.com\">");
		                      out.append("</div>");
		                    out.append("</div>");
		out.append("");
		                    out.append("<div class=\"row mb-3\">");
		                      out.append("<label for=\"Twitter\" class=\"col-md-4 col-lg-3 col-form-label\">Trang Twitter</label>");
		                      out.append("<div class=\"col-md-8 col-lg-9\">");
		                        out.append("<input name=\"twitter\" type=\"text\" class=\"form-control\" id=\"Twitter\" value=\"https://twitter.com/#\">");
		                      out.append("</div>");
		                    out.append("</div>");
		out.append("");
		                    out.append("<div class=\"row mb-3\">");
		                      out.append("<label for=\"Facebook\" class=\"col-md-4 col-lg-3 col-form-label\">Trang Facebook </label>");
		                      out.append("<div class=\"col-md-8 col-lg-9\">");
		                        out.append("<input name=\"facebook\" type=\"text\" class=\"form-control\" id=\"Facebook\" value=\"https://facebook.com/#\">");
		                      out.append("</div>");
		                    out.append("</div>");
		out.append("");
		                    out.append("<div class=\"row mb-3\">");
		                      out.append("<label for=\"Instagram\" class=\"col-md-4 col-lg-3 col-form-label\">Trang Instagram </label>");
		                      out.append("<div class=\"col-md-8 col-lg-9\">");
		                        out.append("<input name=\"instagram\" type=\"text\" class=\"form-control\" id=\"Instagram\" value=\"https://instagram.com/#\">");
		                      out.append("</div>");
		                    out.append("</div>");
		out.append("");
		                    out.append("<div class=\"row mb-3\">");
		                      out.append("<label for=\"Linkedin\" class=\"col-md-4 col-lg-3 col-form-label\">Trang Linkedin</label>");
		                      out.append("<div class=\"col-md-8 col-lg-9\">");
		                        out.append("<input name=\"linkedin\" type=\"text\" class=\"form-control\" id=\"Linkedin\" value=\"https://linkedin.com/#\">");
		                      out.append("</div>");
		                    out.append("</div>");
		out.append("");
		                    out.append("<div class=\"text-center\">");
		                      out.append("<button type=\"submit\" class=\"btn btn-primary\">Lưu thông tin</button>");
		                    out.append("</div>");
		                  out.append("</form><!-- End Profile Edit Form -->");
		out.append("");
		                out.append("</div>");
		out.append("");
		                out.append("<div class=\"tab-pane fade pt-3\" id=\"profile-settings\">");
		out.append("");
		                  out.append("<!-- Settings Form -->");
		                  out.append("<form>");
		out.append("");
		                    out.append("<div class=\"row mb-3\">");
		                      out.append("<label for=\"fullName\" class=\"col-md-4 col-lg-3 col-form-label\">Thông báo email</label>");
		                      out.append("<div class=\"col-md-8 col-lg-9\">");
		                        out.append("<div class=\"form-check\">");
		                          out.append("<input class=\"form-check-input\" type=\"checkbox\" id=\"changesMade\" checked>");
		                          out.append("<label class=\"form-check-label\" for=\"changesMade\">");
		                            out.append("Changes made to your account");
		                          out.append("</label>");
		                        out.append("</div>");
		                        out.append("<div class=\"form-check\">");
		                          out.append("<input class=\"form-check-input\" type=\"checkbox\" id=\"newProducts\" checked>");
		                          out.append("<label class=\"form-check-label\" for=\"newProducts\">");
		                            out.append("Information on new products and services");
		                          out.append("</label>");
		                        out.append("</div>");
		                        out.append("<div class=\"form-check\">");
		                          out.append("<input class=\"form-check-input\" type=\"checkbox\" id=\"proOffers\">");
		                          out.append("<label class=\"form-check-label\" for=\"proOffers\">");
		                            out.append("Marketing and promo offers");
		                          out.append("</label>");
		                        out.append("</div>");
		                        out.append("<div class=\"form-check\">");
		                          out.append("<input class=\"form-check-input\" type=\"checkbox\" id=\"securityNotify\" checked disabled>");
		                          out.append("<label class=\"form-check-label\" for=\"securityNotify\">");
		                            out.append("Security alerts");
		                          out.append("</label>");
		                        out.append("</div>");
		                      out.append("</div>");
		                    out.append("</div>");
		out.append("");
		                    out.append("<div class=\"text-center\">");
		                      out.append("<button type=\"submit\" class=\"btn btn-primary\">Lưu thay đổi</button>");
		                    out.append("</div>");
		                  out.append("</form><!-- End settings Form -->");
		out.append("");
		                out.append("</div>");
		out.append("");
		                out.append("<div class=\"tab-pane fade pt-3\" id=\"profile-change-password\">");
		                  out.append("<!-- Change Password Form -->");
		                  out.append("<form>");
		out.append("");
		                    out.append("<div class=\"row mb-3\">");
		                      out.append("<label for=\"currentPassword\" class=\"col-md-4 col-lg-3 col-form-label\">Mật khẩu hiện tại</label>");
		                      out.append("<div class=\"col-md-8 col-lg-9\">");
		                        out.append("<input name=\"password\" type=\"password\" class=\"form-control\" id=\"currentPassword\">");
		                      out.append("</div>");
		                    out.append("</div>");
		out.append("");
		                    out.append("<div class=\"row mb-3\">");
		                      out.append("<label for=\"newPassword\" class=\"col-md-4 col-lg-3 col-form-label\">Mật khẩu mới</label>");
		                      out.append("<div class=\"col-md-8 col-lg-9\">");
		                        out.append("<input name=\"newpassword\" type=\"password\" class=\"form-control\" id=\"newPassword\">");
		                      out.append("</div>");
		                    out.append("</div>");
		out.append("");
		                    out.append("<div class=\"row mb-3\">");
		                      out.append("<label for=\"renewPassword\" class=\"col-md-4 col-lg-3 col-form-label\">Nhập lại mật khẩu mới</label>");
		                      out.append("<div class=\"col-md-8 col-lg-9\">");
		                        out.append("<input name=\"renewpassword\" type=\"password\" class=\"form-control\" id=\"renewPassword\">");
		                      out.append("</div>");
		                    out.append("</div>");
		out.append("");
		                    out.append("<div class=\"text-center\">");
		                      out.append("<button type=\"submit\" class=\"btn btn-primary\">Đổi mật khẩu</button>");
		                    out.append("</div>");
		                  out.append("</form><!-- End Change Password Form -->");
		out.append("");
		                out.append("</div>");
		out.append("");
		              out.append("</div><!-- End Bordered Tabs -->");
		out.append("");
		            out.append("</div>");
		          out.append("</div>");
		out.append("");
		        out.append("</div>");
		      out.append("</div>");
		    out.append("</section>");
		out.append("");
		  out.append("</main><!-- End #main -->");
		out.append("");
		  out.append("<!-- ======= Footer ======= -->");
		  out.append("<footer id=\"footer\" class=\"footer\">");
		    out.append("<div class=\"copyright\">");
		      out.append("&copy; Copyright <strong><span>NiceAdmin</span></strong>. All Rights Reserved");
		    out.append("</div>");
		    out.append("<div class=\"credits\">");
		      out.append("<!-- All the links in the footer should remain intact. -->");
		      out.append("<!-- You can delete the links only if you purchased the pro version. -->");
		      out.append("<!-- Licensing information: https://bootstrapmade.com/license/ -->");
		      out.append("<!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/ -->");
		      out.append("Designed by <a href=\"https://bootstrapmade.com/\">BootstrapMade</a>");
		    out.append("</div>");
		  out.append("</footer><!-- End Footer -->");
		out.append("");
		  out.append("<a href=\"#\" class=\"back-to-top d-flex align-items-center justify-content-center\"><i class=\"bi bi-arrow-up-short\"></i></a>");
		out.append("");
		  out.append("<!-- Vendor JS Files -->");
		  out.append("<script src=\"assets/vendor/apexcharts/apexcharts.min.js\"></script>");
		  out.append("<script src=\"assets/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>");
		  out.append("<script src=\"assets/vendor/chart.js/chart.umd.js\"></script>");
		  out.append("<script src=\"assets/vendor/echarts/echarts.min.js\"></script>");
		  out.append("<script src=\"assets/vendor/quill/quill.js\"></script>");
		  out.append("<script src=\"assets/vendor/simple-datatables/simple-datatables.js\"></script>");
		  out.append("<script src=\"assets/vendor/tinymce/tinymce.min.js\"></script>");
		  out.append("<script src=\"assets/vendor/php-email-form/validate.js\"></script>");
		out.append("");
		  out.append("<!-- Template Main JS File -->");
		  out.append("<script src=\"assets/js/main.js\"></script>");
		out.append("");
		out.append("</body>");
		out.append("");
		out.append("</html>");
	}

	@Override
	protected void doPost(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
		// TODO Auto-generated method stub
		doGet(req, resp);
	}
	
	

}
