package com.travelvn;

import java.io.IOException;
import java.io.PrintWriter;

import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

@WebServlet("/Tour")
public class TourServlet extends HttpServlet{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Override
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
		 response.setCharacterEncoding("UTF-8");
		 response.setContentType("text/html; charset=UTF-8");

		 PrintWriter out = response.getWriter();
		 out.append("<!DOCTYPE html>");
		 out.append("<html lang=\"en\">");
		 out.append("<head>");
		 out.append("  <meta charset=\"utf-8\">");
		 out.append("  <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\"");
		 out.append("  <title>Quản lý tour</title>");
		 out.append("  <meta content=\"\" name=\"description\">");
		 out.append("  <meta content=\"\" name=\"keywords\">");
		 out.append("  <!-- Favicons -->");
		 out.append("  <link href=\"assets/img/favicon.png\" rel=\"icon\">");
		 out.append("  <link href=\"assets/img/apple-touch-icon.png\" rel=\"apple-touch-icon\">");
		 out.append("  <!-- Google Fonts -->");
		 out.append("  <link href=\"https://fonts.gstatic.com\" rel=\"preconnect\">");
		 out.append("  <link href=\"https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i\" rel=\"stylesheet\">");
		 out.append("  <!-- Vendor CSS Files -->");
		 out.append("  <link href=\"assets/vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">");
		 out.append("  <link href=\"assets/vendor/bootstrap-icons/bootstrap-icons.css\" rel=\"stylesheet\">");
		 out.append("  <link href=\"assets/vendor/boxicons/css/boxicons.min.css\" rel=\"stylesheet\">");
		 out.append("  <link href=\"assets/vendor/quill/quill.snow.css\" rel=\"stylesheet\">");
		 out.append("  <link href=\"assets/vendor/quill/quill.bubble.css\" rel=\"stylesheet\">");
		 out.append("  <link href=\"assets/vendor/remixicon/remixicon.css\" rel=\"stylesheet\">");
		 out.append("  <link href=\"assets/vendor/simple-datatables/style.css\" rel=\"stylesheet\">");
		 out.append("");
		 out.append("  <!-- Template Main CSS File -->");
		 out.append("  <link href=\"css/style.css\" rel=\"stylesheet\">");
		 out.append("</head>");
		 out.append("");
		 out.append("<body>");
		 out.append("");
		 out.append(" <!-- ======= Header ======= -->");
		 out.append(" <header id=\"header\" class=\"header fixed-top d-flex align-items-center\">");
		 out.append("");
		 out.append("  <div class=\"d-flex align-items-center justify-content-between\">");
		 out.append("    <a href=\"index.html\" class=\"logo d-flex align-items-center\" style=\"height: max-content;\">");
		 out.append("      <img src=\"resources/Asset 2.svg\" alt=\"\" style=\"height: 100px; width: 40px;\" >");
		 out.append("      <span class=\"d-none d-lg-block\">TravelVN</span>");
		 out.append("    </a>");
		 out.append("  </div><!-- End Logo -->");
		 out.append("  <i class=\"bi bi-list toggle-sidebar-btn\"></i>");
		 out.append("");
		 out.append("  <div class=\"search-bar\">");
		 out.append("    <form class=\"search-form d-flex align-items-center\" method=\"GET\" action=\"#\">");
		 out.append("      <input type=\"text\" name=\"query\" placeholder=\"Tìm kiếm\" title=\"Enter search keyword\" id=\"name\">");
		 out.append("      <button type=\"submit\" title=\"Search\"><i class=\"bi bi-search\" onclick=getData()></i></button>");
		 out.append("    </form>");
		 out.append("  </div><!-- End Search Bar -->");
		 out.append("");
		 out.append("  <nav class=\"header-nav ms-auto\">");
		 out.append("    <ul class=\"d-flex align-items-center\">");
		 out.append("");
		 out.append("      <li class=\"nav-item d-block d-lg-none\">");
		 out.append("        <a class=\"nav-link nav-icon search-bar-toggle \" href=\"#\">");
		 out.append("          <i class=\"bi bi-search\"></i>");
		 out.append("        </a>");
		 out.append("      </li><!-- End Search Icon-->");
		 out.append("");
		 out.append("      <li class=\"nav-item dropdown\">");
		 out.append("");
		 out.append("        <a class=\"nav-link nav-icon\" href=\"#\" data-bs-toggle=\"dropdown\">");
		 out.append("          <i class=\"bi bi-bell\"></i>");
		 out.append("          <span class=\"badge bg-primary badge-number\">4</span>");
		 out.append("        </a><!-- End Notification Icon -->");
		 out.append("");
		 out.append("        <ul class=\"dropdown-menu dropdown-menu-end dropdown-menu-arrow notifications\">");
		 out.append("          <li class=\"dropdown-header\">");
		 out.append("            You have 4 new notifications");
		 out.append("            <a href=\"#\"><span class=\"badge rounded-pill bg-primary p-2 ms-2\">View all</span></a>");
		 out.append("          </li>");
		 out.append("          <li>");
		 out.append("            <hr class=\"dropdown-divider\">");
		 out.append("          </li>");
		 out.append("");
		 out.append("          <li class=\"notification-item\">");
		 out.append("            <i class=\"bi bi-exclamation-circle text-warning\"></i>");
		 out.append("            <div>");
		 out.append("              <h4>Lorem Ipsum</h4>");
		 out.append("              <p>Quae dolorem earum veritatis oditseno</p>");
		 out.append("              <p>30 min. ago</p>");
		 out.append("            </div>");
		 out.append("          </li>");
		 out.append("");
		 out.append("          <li>");
		 out.append("            <hr class=\"dropdown-divider\">");
		 out.append("          </li>");
		 out.append("");
		 out.append("          <li class=\"notification-item\">");
		 out.append("            <i class=\"bi bi-x-circle text-danger\"></i>");
		 out.append("            <div>");
		 out.append("              <h4>Atque rerum nesciunt</h4>");
		 out.append("              <p>Quae dolorem earum veritatis oditseno</p>");
		 out.append("              <p>1 hr. ago</p>");
		 out.append("            </div>");
		 out.append("          </li>");
		 out.append("");
		 out.append("          <li>");
		 out.append("            <hr class=\"dropdown-divider\">");
		 out.append("          </li>");
		 out.append("");
		 out.append("          <li class=\"notification-item\">");
		 out.append("            <i class=\"bi bi-check-circle text-success\"></i>");
		 out.append("            <div>");
		 out.append("              <h4>Sit rerum fuga</h4>");
		 out.append("              <p>Quae dolorem earum veritatis oditseno</p>");
		 out.append("              <p>2 hrs. ago</p>");
		 out.append("            </div>");
		 out.append("          </li>");
		 out.append("");
		 out.append("          <li>");
		 out.append("            <hr class=\"dropdown-divider\">");
		 out.append("          </li>");
		 out.append("");
		 out.append("          <li class=\"notification-item\">");
		 out.append("            <i class=\"bi bi-info-circle text-primary\"></i>");
		 out.append("            <div>");
		 out.append("              <h4>Dicta reprehenderit</h4>");
		 out.append("              <p>Quae dolorem earum veritatis oditseno</p>");
		 out.append("              <p>4 hrs. ago</p>");
		 out.append("            </div>");
		 out.append("          </li>");
		 out.append("");
		 out.append("          <li>");
		 out.append("            <hr class=\"dropdown-divider\">");
		 out.append("          </li>");
		 out.append("          <li class=\"dropdown-footer\">");
		 out.append("            <a href=\"#\">Show all notifications</a>");
		 out.append("          </li>");
		 out.append("");
		 out.append("        </ul><!-- End Notification Dropdown Items -->");
		 out.append("");
		 out.append("      </li><!-- End Notification Nav -->");
		 out.append("");
		 out.append("      <li class=\"nav-item dropdown\">");
		 out.append("");
		 out.append("        <a class=\"nav-link nav-icon\" href=\"#\" data-bs-toggle=\"dropdown\">");
		 out.append("          <i class=\"bi bi-chat-left-text\"></i>");
		 out.append("          <span class=\"badge bg-success badge-number\">3</span>");
		 out.append("        </a><!-- End Messages Icon -->");
		 out.append("");
		 out.append("        <ul class=\"dropdown-menu dropdown-menu-end dropdown-menu-arrow messages\">");
		 out.append("          <li class=\"dropdown-header\">");
		 out.append("            You have 3 new messages");
		 out.append("            <a href=\"#\"><span class=\"badge rounded-pill bg-primary p-2 ms-2\">View all</span></a>");
		 out.append("          </li>");
		 out.append("          <li>");
		 out.append("            <hr class=\"dropdown-divider\">");
		 out.append("          </li>");
		 out.append("");
		 out.append("          <li class=\"message-item\">");
		 out.append("            <a href=\"#\">");
		 out.append("              <img src=\"assets/img/messages-1.jpg\" alt=\"\" class=\"rounded-circle\">");
		 out.append("              <div>");
		 out.append("                <h4>Maria Hudson</h4>");
		 out.append("                <p>Velit asperiores et ducimus soluta repudiandae labore officia est ut...</p>");
		 out.append("                <p>4 hrs. ago</p>");
		 out.append("              </div>");
		 out.append("            </a>");
		 out.append("          </li>");
		 out.append("          <li>");
		 out.append("            <hr class=\"dropdown-divider\">");
		 out.append("          </li>");
		 out.append("");
		 out.append("          <li class=\"message-item\">");
		 out.append("            <a href=\"#\">");
		 out.append("              <img src=\"assets/img/messages-2.jpg\" alt=\"\" class=\"rounded-circle\">");
		 out.append("              <div>");
		 out.append("                <h4>Anna Nelson</h4>");
		 out.append("                <p>Velit asperiores et ducimus soluta repudiandae labore officia est ut...</p>");
		 out.append("                <p>6 hrs. ago</p>");
		 out.append("              </div>");
		 out.append("            </a>");
		 out.append("          </li>");
		 out.append("          <li>");
		 out.append("            <hr class=\"dropdown-divider\">");
		 out.append("          </li>");
		 out.append("");
		 out.append("          <li class=\"message-item\">");
		 out.append("            <a href=\"#\">");
		 out.append("              <img src=\"assets/img/messages-3.jpg\" alt=\"\" class=\"rounded-circle\">");
		 out.append("              <div>");
		 out.append("                <h4>David Muldon</h4>");
		 out.append("                <p>Velit asperiores et ducimus soluta repudiandae labore officia est ut...</p>");
		 out.append("                <p>8 hrs. ago</p>");
		 out.append("              </div>");
		 out.append("            </a>");
		 out.append("          </li>");
		 out.append("          <li>");
		 out.append("            <hr class=\"dropdown-divider\">");
		 out.append("          </li>");
		 out.append("");
		 out.append("          <li class=\"dropdown-footer\">");
		 out.append("            <a href=\"#\">Show all messages</a>");
		 out.append("          </li>");
		 out.append("");
		 out.append("        </ul><!-- End Messages Dropdown Items -->");
		 out.append("");
		 out.append("      </li><!-- End Messages Nav -->");
		 out.append("");
		 out.append("      <li class=\"nav-item dropdown pe-3\">");
		 out.append("");
		 out.append("        <a class=\"nav-link nav-profile d-flex align-items-center pe-0\" href=\"#\" data-bs-toggle=\"dropdown\">");
		 out.append("          <img src=\"assets/img/profile-img.jpg\" alt=\"Profile\" class=\"rounded-circle\">");
		 out.append("          <span class=\"d-none d-md-block dropdown-toggle ps-2\">Kiều Đức Thịnh</span>");
		 out.append("        </a><!-- End Profile Iamge Icon -->");
		 out.append("");
		 out.append("        <ul class=\"dropdown-menu dropdown-menu-end dropdown-menu-arrow profile\">");
		 out.append("          <li class=\"dropdown-header\">");
		 out.append("            <h6>Kiều Đức Thịnh</h6>");
		 out.append("            <span>Business analyst</span>");
		 out.append("          </li>");
		 out.append("          <li>");
		 out.append("            <hr class=\"dropdown-divider\">");
		 out.append("          </li>");
		 out.append("");
		 out.append("          <li>");
		 out.append("            <a class=\"dropdown-item d-flex align-items-center\" href=\"users-profile.html\">");
		 out.append("              <i class=\"bi bi-person\"></i>");
		 out.append("              <span>Hồ sơ cá nhân</span>");
		 out.append("            </a>");
		 out.append("          </li>");
		 out.append("          <li>");
		 out.append("            <hr class=\"dropdown-divider\">");
		 out.append("          </li>");
		 out.append("");
		 out.append("          <li>");
		 out.append("            <a class=\"dropdown-item d-flex align-items-center\" href=\"users-profile.html\">");
		 out.append("              <i class=\"bi bi-gear\"></i>");
		 out.append("              <span>Cài đặt tài khoản</span>");
		 out.append("            </a>");
		 out.append("          </li>");
		 out.append("          <li>");
		 out.append("            <hr class=\"dropdown-divider\">");
		 out.append("          </li>");
		 out.append("");
		 out.append("          <li>");
		 out.append("            <a class=\"dropdown-item d-flex align-items-center\" href=\"pages-faq.html\">");
		 out.append("              <i class=\"bi bi-question-circle\"></i>");
		 out.append("              <span>Trợ giúp</span>");
		 out.append("            </a>");
		 out.append("          </li>");
		 out.append("          <li>");
		 out.append("            <hr class=\"dropdown-divider\">");
		 out.append("          </li>");
		 out.append("");
		 out.append("          <li>");
		 out.append("            <a class=\"dropdown-item d-flex align-items-center\" href=\"#\">");
		 out.append("              <i class=\"bi bi-box-arrow-right\"></i>");
		 out.append("              <span>Đăng xuất</span>");
		 out.append("            </a>");
		 out.append("          </li>");
		 out.append("");
		 out.append("        </ul><!-- End Profile Dropdown Items -->");
		 out.append("      </li><!-- End Profile Nav -->");
		 out.append("");
		 out.append("    </ul>");
		 out.append("  </nav><!-- End Icons Navigation -->");
		 out.append("");
		 out.append("</header><!-- End Header -->");
		 out.append("");
		 out.append("  <!-- ======= Sidebar ======= -->");
		 out.append("  <aside id=\"sidebar \" class=\"sidebar\">");
		 out.append("");
		 out.append("    <ul class=\"sidebar-nav\" id=\"sidebar-nav\">");
		 out.append("");
		 out.append("      <li class=\"nav-item\">");
		 out.append("        <a class=\"nav-link \" href=\"index.html\">");
		 out.append("          <i class=\"bi bi-grid\"></i>");
		 out.append("          <span>Dashboard</span>");
		 out.append("        </a>");
		 out.append("      </li><!-- End Dashboard Nav -->");
		 out.append("");
		 out.append("      <li class=\"nav-item\">");
		 out.append("        <a class=\"nav-link collapsed\"  href=\"Tour_management.html\">");
		 out.append("          <i class=\"bi bi-layout-text-window-reverse\"></i><span>Quản lý tour</span>");
		 out.append("        <ul id=\"tables-nav\" class=\"nav-content collapse \" data-bs-parent=\"#sidebar-nav\">");
		 out.append("          <li>");
		 out.append("            <a href=\"tables-general.html\">");
		 out.append("              <i class=\"bi bi-circle\"></i><span>Table general</span>");
		 out.append("            </a>");
		 out.append("          </li>");
		 out.append("          <li>");
		 out.append("            <a href=\"Tour_unit_management.html\">");
		 out.append("              <i class=\"bi bi-circle\"></i><span>Danh sách tour</span>");
		 out.append("            </a>");
		 out.append("          </li>");
		 out.append("        </ul>");
		 out.append("      </li><!-- End Tables Nav -->");
		 out.append("");
		 out.append("      <li class=\"nav-item\">");
		 out.append("        <a class=\"nav-link collapsed\" data-bs-target=\"#charts-nav\" href=\"Festival_management.html\">");
		 out.append("          <i class=\"bi bi-flower1\"></i>");
		 out.append("");
		 out.append("    <span>Quản lý lễ hội</span>");
		 out.append("        </a>");
		 out.append("      </li><!-- End Charts Nav -->");
		 out.append("      <li class=\"nav-item\">");
		 out.append("        <a class=\"nav-link collapsed\" data-bs-target=\"#charts-nav\" href=\"Discount-management.html\">");
		 out.append("          <i class=\"bi bi-coin\"></i>");
		 out.append("");
		 out.append("    <span>Chương trình giảm giá</span>");
		 out.append("        </a>");
		 out.append("      </li><!-- End Charts Nav -->");
		 out.append("      <li class=\"nav-item\">");
		 out.append("        <a class=\"nav-link collapsed\" data-bs-target=\"#charts-nav\" href=\"tour_guide_management.html\">");
		 out.append("          <i class=\"bi bi-flag-fill\"></i>");
		 out.append("");
		 out.append("    <span>Hướng dẫn viên</span>");
		 out.append("        </a>");
		 out.append("      </li><!-- End Charts Nav -->");
		 out.append("");
		 out.append("      ");
		 out.append("      <li class=\"nav-item\">");
		 out.append("        <a class=\"nav-link collapsed\" data-bs-target=\"#charts-nav\" href=\"approve_request_cancel_booking.html\">");
		 out.append("          <i class=\"bi bi-card-checklist\"></i>");
		 out.append("          <span>Yêu cầu huỷ tour</span>");
		 out.append("        </a>");
		 out.append("      </li>");
		 out.append("      <li class=\"nav-item\">");
		 out.append("        <a class=\"nav-link collapsed\" data-bs-target=\"#charts-nav\" href=\"Customer_info_management.html\">");
		 out.append("          <i class=\"bi bi-people-fill\"></i>");
		 out.append("          <span>Khách hàng</span>");
		 out.append("        </a>");
		 out.append("      </li><!-- End Charts Nav -->");
		 out.append("");
		 out.append("");
		 out.append("      <li class=\"nav-item\">");
		 out.append("        <a class=\"nav-link collapsed\" href=\"users-profile.html\">");
		 out.append("          <i class=\"bi bi-person\"></i>");
		 out.append("          <span>Thông tin cá nhân</span>");
		 out.append("        </a>");
		 out.append("      </li><!-- End Profile Page Nav -->");
		 out.append("");
		 out.append("      <li class=\"nav-heading\">Khác</li>");
		 out.append("");
		 out.append("");
		 out.append("      <li class=\"nav-item\">");
		 out.append("        <a class=\"nav-link collapsed\" href=\"pages-faq.html\">");
		 out.append("          <i class=\"bi bi-question-circle\"></i>");
		 out.append("          <span>Hướng dẫn sử dụng</span>");
		 out.append("        </a>");
		 out.append("      </li><!-- End F.A.Q Page Nav -->");
		 out.append("");
		 out.append("      <li class=\"nav-item\">");
		 out.append("        <a class=\"nav-link collapsed\" href=\"pages-contact.html\">");
		 out.append("          <i class=\"bi bi-envelope\"></i>");
		 out.append("          <span>Liên hệ với admin</span>");
		 out.append("        </a>");
		 out.append("      </li><!-- End Contact Page Nav -->");
		 out.append("      <li class=\"nav-item\">");
		 out.append("        <a class=\"nav-link collapsed\" href=\"pages-contact.html\">");
		 out.append("          <i class=\"bi bi-gear\"></i>");
		 out.append("          <span>Cài đặt</span>");
		 out.append("        </a>");
		 out.append("      </li><!-- End Contact Page Nav -->");
		 out.append("");
		 out.append("");
		 out.append("    </ul>");
		 out.append("");
		 out.append("  </aside><!-- End Sidebar-->");
		 out.append("");
		 out.append("  <main id=\"main\" class=\"main\">");
		 out.append("");
		 out.append("    <div class=\"pagetitle d-flex\">");
		 out.append("      <h1 class=\"align-middle\">Danh sách tour</h1>");
		 out.append("      <nav class=\"ms-auto\">");
		 out.append("        <ol class=\"breadcrumb\">");
		 out.append("          <li class=\"breadcrumb-item\"><a href=\"index.html\"><i class=\"bi bi-house-door\"></i></a></li>");
		 out.append("          <li class=\"breadcrumb-item\">Quản lý tour</li>");
		 out.append("        </ol>");
		 out.append("      </nav>");
		 out.append("    </div><!-- End Page Title -->");
		 out.append("");
		 out.append("    <section class=\"section\">");
		 out.append("      <div class=\"row d-flex\">");
		 out.append("      <div class=\"col-sm-9 fixed-filter ms-auto\">");
		 out.append("            <a href=\"add-tour.html\" class=\"btn btn-success\"><i class=\"bi bi-plus-circle\"></i>");
		 out.append("              Thêm tour mới ");
		 out.append("            </a>");
		 out.append("        </div>");
		 out.append("        <div class=\"col-sm-3 fixed-filter ms-auto\">");
		 out.append("          <div class=\"card mb-3 form-floating\">");
		 out.append("              <form class=\"d-flex\" role=\"search\" method=\"POST\" action=\"#\">");
		 out.append("                <input type=\"text\" class=\"form-control\" id=\"tourName\" placeholder=\"Tên tour\" >");
		 out.append("                <button type=\"submit\" class=\"btn btn-primary\">");
		 out.append("                  <i class=\"bi bi-search\"></i>");
		 out.append("                </button>");
		 out.append("              </form>");
		 out.append("          </div>");
		 out.append("        </div>");
		 out.append("      </div>");
		 out.append("  ");
		 out.append("");
		 out.append("        <div class=\"row\">");
		 out.append("          <!-- ...existing code... -->");
		 out.append("<!-- ...existing code... -->");
		 out.append("        <div class=\"col-sm-12\">");
		 out.append("      ");
		 out.append("    ");
		 out.append("              <div class=\"card mb-3\">");
		 out.append("                <div class=\"row g-0\">");
		 out.append("                  ");
		 out.append("                  <div class=\"col-md-4\">");
		 out.append("                    ");
		 out.append("                    <a href=\"Tour-Detail\">");
		 out.append("                    <img  src=\"assets/img/chi-phi-di-da-lat-1.jpeg\" class=\"img-fluid rounded-start\" alt=\"...\">");
		 out.append("                  </a>");
		 out.append("                  </div>");
		 out.append("                  ");
		 out.append("                  <div class=\"col-md-8\">");
		 out.append("                    <div class=\"card-body\">");
		 out.append("                    <div class=\"d-flex row\">");
		 out.append("                      <a href=\"Tour_Detail\" class=\"col-sm-8\">");
		 out.append("                      <h5 class=\"card-title\">Đà Lạt 3 Ngày 2 đêm</h5>");
		 out.append("                    </a>");
		 out.append("                    <a href=\"edit-tour.html\" class=\"fw-bold col-sm-2 mt-3 text-end\"> ");
		 out.append("                      <i class=\"bi bi-gear-fill text-warning\"></i>");
		 out.append("                    </a>");
		 out.append("                    <a href=\"Tour_unit_management.html\" class=\"fw-bold col-sm-2 mt-3 text-end\"> ");
		 out.append("                      <i class=\"bi bi-trash3-fill text-danger\"></i>");
		 out.append("          ");
		 out.append("                    </a>");
		 out.append("                  </div>");
		 out.append("                  <div class=\"row\">");
		 out.append("                  <div class=\"col-md-6\">");
		 out.append("                    <p class=\"card-text\"><strong>Mã tour:</strong> T001-00001</p>");
		 out.append("                    <p class=\"card-text\"><strong>Thời lượng:</strong> 3 Ngày 2 Đêm</p>");
		 out.append("                    <p class=\"card-text\"><strong>Phương tiện:</strong> Ô tô, Máy bay</p>");
		 out.append("                    <p class=\"card-text\"><strong>Điểm đi:</strong> Hà Nội</p>");
		 out.append("                    <p class=\"card-text\"><strong>Điểm đến:</strong> Đà Lạt</p>");
		 out.append("                  </div>");
		 out.append("                    <div class=\"col-md-6\">");
		 out.append("                      <p class=\"card-text\"><strong>Thời điểm tạo:</strong> 2025-04-01</p>");
		 out.append("                      <p class=\"card-text\"><strong>Thời điểm cập nhật gần nhất:</strong> 2025-04-07</p>");
		 out.append("                      <p class=\"card-text\"><strong>Người điều hành sửa gần nhất:</strong> Nguyễn Văn A</p>");
		 out.append("                      <p class=\"card-text\"><strong>Thể loại:</strong> Du lịch nghỉ dưỡng</p>");
		 out.append("                    </div>");
		 out.append("                  </div>");
		 out.append("                  </div>");
		 out.append("          ");
		 out.append("                   ");
		 out.append("                  </div>");
		 out.append("                </div>");
		 out.append("              </div><!-- End Card with an image on left -->");
		 out.append("");
		 out.append("              <div class=\"card mb-3\">");
		 out.append("                <div class=\"row g-0\">");
		 out.append("                  <div class=\"col-md-4\">");
		 out.append("                    <a href=\"Tour_detail.html\">");
		 out.append("                    <img src=\"assets/img/chi-phi-di-da-lat-1.jpeg\" class=\"img-fluid rounded-start\" alt=\"...\">");
		 out.append("                  </a>");
		 out.append("                  </div>");
		 out.append("                  <div class=\"col-md-8\">");
		 out.append("                  ");
		 out.append("                    <div class=\"card-body\">");
		 out.append("                      <div class=\"d-flex row\">");
		 out.append("                      <a href=\"Tour_detail.html\" class=\"col-sm-8\">");
		 out.append("                      <h5 class=\"card-title\">Đà Lạt 3 Ngày 2 đêm</h5>");
		 out.append("                    </a>");
		 out.append("                    <a href=\"Tour_unit_management.html\" class=\"fw-bold col-sm-2 mt-3 text-end\"> ");
		 out.append("                      <i class=\"bi bi-gear-fill text-warning\"></i>");
		 out.append("                    </a>");
		 out.append("                    <a href=\"Tour_unit_management.html\" class=\"fw-bold col-sm-2 mt-3 text-end\"> ");
		 out.append("                      <i class=\"bi bi-trash3-fill text-danger\"></i>");
		 out.append("          ");
		 out.append("                    </a>");
		 out.append("                  </div>");
		 out.append("                      <p class=\"card-text\">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>");
		 out.append("          ");
		 out.append("                    </div>");
		 out.append("                  </div>");
		 out.append("                </div>");
		 out.append("              </div><!-- End Card with an image on left -->");
		 out.append("  ");
		 out.append("              <div class=\"card mb-3\">");
		 out.append("                <div class=\"row g-0\">");
		 out.append("                  <div class=\"col-md-4\">");
		 out.append("                    <a href=\"Tour_detail.html\">");
		 out.append("                    <img src=\"assets/img/481088087_959148229729702_4478781852400038459_n.jpg\" class=\"img-fluid rounded-start\" alt=\"...\">");
		 out.append("                  </a>");
		 out.append("                  </div>");
		 out.append("                  <div class=\"col-md-8\">");
		 out.append("                  ");
		 out.append("                    <div class=\"card-body\">");
		 out.append("                      <div class=\"d-flex row\">");
		 out.append("                      <a href=\"Tour_detail.html\" class=\"col-sm-8\">");
		 out.append("                      <h5 class=\"card-title\">Đà Lạt 3 Ngày 2 đêm</h5>");
		 out.append("                    </a>");
		 out.append("                    <a href=\"Tour_unit_management.html\" class=\"fw-bold col-sm-2 mt-3 text-end\"> ");
		 out.append("                      <i class=\"bi bi-gear-fill text-warning\"></i>");
		 out.append("                    </a>");
		 out.append("                    <a href=\"Tour_unit_management.html\" class=\"fw-bold col-sm-2 mt-3 text-end\"> ");
		 out.append("                      <i class=\"bi bi-trash3-fill text-danger\"></i>");
		 out.append("          ");
		 out.append("                    </a>");
		 out.append("                  </div>");
		 out.append("                      <p class=\"card-text\">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>");
		 out.append("          ");
		 out.append("                    </div>");
		 out.append("                  </div>");
		 out.append("                </div>");
		 out.append("              </div><!-- End Card with an image on left -->");
		 out.append(" ");
		 out.append("              <div class=\"card mb-3\">");
		 out.append("                <div class=\"row g-0\">");
		 out.append("                  <div class=\"col-md-4\">");
		 out.append("                    <a href=\"Tour_detail.html\">");
		 out.append("                    <img src=\"assets/img/481088087_959148229729702_4478781852400038459_n.jpg\" class=\"img-fluid rounded-start\" alt=\"...\">");
		 out.append("                  </a>");
		 out.append("                  </div>");
		 out.append("                  <div class=\"col-md-8\">");
		 out.append("                  ");
		 out.append("                    <div class=\"card-body\">");
		 out.append("                      <div class=\"d-flex row\">");
		 out.append("                      <a href=\"Tour_detail.html\" class=\"col-sm-8\">");
		 out.append("                      <h5 class=\"card-title\">Đà Lạt 3 Ngày 2 đêm</h5>");
		 out.append("                    </a>");
		 out.append("                    <a href=\"Tour_unit_management.html\" class=\"fw-bold col-sm-2 mt-3 text-end\"> ");
		 out.append("                      <i class=\"bi bi-gear-fill text-warning\"></i>");
		 out.append("                    </a>");
		 out.append("                    <a href=\"Tour_unit_management.html\" class=\"fw-bold col-sm-2 mt-3 text-end\"> ");
		 out.append("                      <i class=\"bi bi-trash3-fill text-danger\"></i>");
		 out.append("          ");
		 out.append("                    </a>");
		 out.append("                  </div>");
		 out.append("                      <p class=\"card-text\">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>");
		 out.append("          ");
		 out.append("                    </div>");
		 out.append("                  </div>");
		 out.append("                </div>");
		 out.append("              </div><!-- End Card with an image on left -->");
		 out.append("    </a>");
		 out.append("      </div>");
		 out.append("    </div>");
		 out.append("    <nav aria-label=\"Page navigation example\">");
		 out.append("      <ul class=\"pagination justify-content-center\">");
		 out.append("        <li class=\"page-item \"><a class=\"page-link\" href=\"#\"><i class=\"bi bi-arrow-left\"></i>");
		 out.append("        </a></li>");
		 out.append("        <li class=\"page-item active\"><a class=\"page-link\" href=\"#\">1</a></li>");
		 out.append("        <li class=\"page-item\"><a class=\"page-link\" href=\"#\">2</a></li>");
		 out.append("        <li class=\"page-item\"><a class=\"page-link\" href=\"#\">3</a></li>");
		 out.append("        <li class=\"page-item\"><a class=\"page-link\" href=\"#\">...</a></li>");
		 out.append("        <li class=\"page-item\"><a class=\"page-link\" href=\"#\">7</a></li>");
		 out.append("");
		 out.append("        <li class=\"page-item\"><a class=\"page-link\" href=\"#\"><i class=\"bi bi-arrow-right\"></i></a></li>");
		 out.append("      </ul>");
		 out.append("    </nav><!-- End Basic Pagination -->");
		 out.append("    </section>");
		 out.append("");
		 out.append("  <!-- Lớp phủ -->");
		 out.append("  ");
		 out.append("");
		 out.append("  </main><!-- End #main -->");
		 out.append("");
		 out.append("  <!-- ======= Footer ======= -->");
		 out.append("  <footer id=\"footer\" class=\"footer\">");
		 out.append("    <div class=\"copyright\">");
		 out.append("      &copy; Copyright <strong><span>NiceAdmin</span></strong>. All Rights Reserved");
		 out.append("    </div>");
		 out.append("    <div class=\"credits\">");
		 out.append("      <!-- All the links in the footer should remain intact. -->");
		 out.append("      <!-- You can delete the links only if you purchased the pro version. -->");
		 out.append("      <!-- Licensing information: https://bootstrapmade.com/license/ -->");
		 out.append("      <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/ -->");
		 out.append("      Designed by <a href=\"https://bootstrapmade.com/\">BootstrapMade</a>");
		 out.append("    </div>");
		 out.append("  </footer><!-- End Footer -->");
		 out.append("");
		 out.append("  <a href=\"#\" class=\"back-to-top d-flex align-items-center justify-content-center\"><i class=\"bi bi-arrow-up-short\"></i></a>");
		 out.append("");
		 out.append("  <!-- Vendor JS Files -->");
		 out.append("  <script src=\"assets/vendor/apexcharts/apexcharts.min.js\"></script>");
		 out.append("  <script src=\"assets/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>");
		 out.append("  <script src=\"assets/vendor/chart.js/chart.umd.js\"></script>");
		 out.append("  <script src=\"assets/vendor/echarts/echarts.min.js\"></script>");
		 out.append("  <script src=\"assets/vendor/quill/quill.js\"></script>");
		 out.append("  <script src=\"assets/vendor/simple-datatables/simple-datatables.js\"></script>");
		 out.append("  <script src=\"assets/vendor/tinymce/tinymce.min.js\"></script>");
		 out.append("  <script src=\"assets/vendor/php-email-form/validate.js\"></script>");
		 out.append("  <!-- Template Main JS File -->");
		 out.append("  <script src=\"assets/js/main.js\"></script>");
		 out.append("");
		 out.append("</body>");
		 out.append("");
		 out.append("</html>");
		    
	}

	@Override
	protected void doPost(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
		// TODO Auto-generated method stub
		
		doGet(req, resp);
	}
	
	

}
